### PR TITLE
doc & test API copy between projects

### PR DESCRIPTION
**Pull request by DrXyzzy**
Ref: #1987 and #1988.

API calls `copy_path_between_projects` and `copy_public_path_between_projects`.
```
~/cocalc/src/smc-hub$ mocha test/api
... 
  90 passing (32s)
  1 pending
```

### CODE REVIEW

**Comment by haraldschilly** [comment]
In general, positive review, I also checked that the variables in the test are fine and really check what they say. However, I'm wondering if the second case for copying a subdirectory shouldn't actually use a directory as path argument? I.e. in that test there is `path2`, but at the top you define `path2dir = path2.split('/')[0]`  and never use it.

**Comment by haraldschilly** [comment]
and I have my own little issues running the actual tests. it says `error: unknown option '--compilers'`

**Comment by haraldschilly** [comment]
Above is also a tiny commit to reorganize the npm run test command in smc-hub.

**Comment by DrXyzzy** [comment]
Thanks for review. `pathdir` is dead code and can be deleted.
I'm not sure what happens if `target_path` ends with a slash. I can test it.

**Comment by haraldschilly** [comment]
Just to clarify, I think we should test copying directories here. Hence I think all it needs is to change `path2` to `path2dir` in that test case?

**Comment by williamstein** [comment]
Ping -- this seems forgotton.  @DrXyzzy

**Comment by DrXyzzy** [comment]
Not forgotten. I'm working on it now. Took a detour to go after process/mem leaks from mocha test runs.

**Comment by DrXyzzy** [comment]
@haraldschilly, test cases added for 'file to directory' and 'directory to directory'

**Comment by DrXyzzy** [comment]
I just added the 4-character change in message.coffee to remove `jupyter_port` from the API.
Ref: #2067

**Comment by DrXyzzy** [comment]
> [@haraldschilly] it says error: unknown option '--compilers'

I am getting the `unknown option '--compilers'` error now suddenly too, and I don't see anything in git diffs to explain it. Did we switch versions of node or npm? Anyway, workarounds are either
- use one of the npm rules, e.g. `npm run testapi`, or
- add explicit path to opts file, e.g.
```
~/cocalc/src/smc-hub$ mocha --opts test/mocha.opts test/api
```

**Comment by haraldschilly** [comment]
yes, it's weird, `--compilers` appears in `smc-hub/test/mocha.opts` ... but why does it work when you pass it as `--opts` ? it must be related to a newer version of mocha.

**Pull request merged**
