### PR TITLE
tsx jupyter

### PR DESCRIPTION
**Pull request by tscholl2**
translate jupyter2 to typescript

### CODE REVIEW

**Comment by johnjeng** [comment]
Does this need review or is it work in progress?

**Comment by tscholl2** [comment]
@johnjeng Work in progress still. Kevin reported a possible issue with multiple cursors. I'm waiting for my flight back right now, so I'm hoping to get to it this weekend when I'm back.

**Comment by johnjeng** [comment]
I don't see any glaring errors. @DrXyzzy Can you test this with some of your worksheets?

**Comment by williamstein** [comment]
@DrXyzzy any testing?

**Pull request merged**
