### PR TITLE
preflight: ban specific chrome 77 

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
* extracting exact chrome version as a quadruple of integers
* testing them against what's in the chromium bugreport

# Testing Steps
I tweaked the numbers in the test to ban myself. Numbers are also parsed correctly.

I should check with browserstack edge, FF, etc. ... but I don't see how this could break.

Did the above, looks good. Money shot:

Screenshot from 2019-10-08 15-00-56

# Relevant Issues

 #4136

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by williamstein** [comment]
This is good, but I think we should wait a significant amount of time (a couple of weeks) after this is fixed upstream before rolling it out.  Reasons:

1. We do have a message with a reliable workaround (open a new tab) that does get triggered when the problem happens.
2. I used cocalc with broken chrome 77 all day long actively... without any trouble (since I didn't hit the 256 reconnect limit).

**Comment by williamstein** [comment]
Also, I have a problem with the wording of the message, since it says "You cannot use cocalc with your current browser because..." but that is **simply not true**.   What happens in this instance is you can't use cocalc after 255 failed websocket connection attempts.   In some situations things could work perfectly for many days before hitting that, and for others it could be quicker.

**Comment by williamstein** [comment]
I wonder how quickly chromium really gets updated in the wild?   I may have to do more to try to workaround this bug, since it's pretty severe.   E.g., looking at today on Google analytics we have nearly 70% of users are using chrome, and of those well over 70% are using the version that has this bug.  So _right now_ the vast majority of users are using a version of Chrome that has this websocket bug.

image

**Comment by williamstein** [comment]
I'm setting this to blocked, since there is no way we're banning the browser 60% of users are using to connect to cocalc.com right now.

**Comment by haraldschilly** [comment]
today we seemed to have passed >50% for 77-subreleases >= 114

**Comment by williamstein** [comment]
> today we seemed to have passed >50% for 77-subreleases >= 114

Nice. And yet I'm still stuck on 105 because I'm using ChromeOS... on Google's flagship Pixel Slate nonetheless.  The fact that Chrome can't be updated without a full OS update, and those are rolled out much more slowly, is a major con of this platform.

**Comment by haraldschilly** [comment]
yes, that's not so good. I bet they patch it a little bit for chrome OS and hence it's lagging behind.

**Comment by williamstein** [comment]
Interestingly, this code breaks when doing the build on Kubernetes/docker:
```
[2604] multi ./webapp-lib/primus/primus-engine.min.js 28 bytes {0} [built]
    + 2591 hidden modules

ERROR in /cocalc/src/webapp-lib/preflight-checks.ts
[tsl] ERROR in /cocalc/src/webapp-lib/preflight-checks.ts(148,16)
      TS2532: Object is possibly 'undefined'.

ERROR in /cocalc/src/webapp-lib/preflight-checks.ts
[tsl] ERROR in /cocalc/src/webapp-lib/preflight-checks.ts(148,29)
      TS2339: Property 'join' does not exist on type 'string | number[]'.
  Property 'join' does not exist on type 'string'.
Child html-webpack-plugin for "app.html":
```

I'll fix...

**Pull request merged**
