### PR TITLE
webapp build: cleanup all of "our" package-lock files

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
This removes all of "our" (in the cocalc codebase) package-lock files, upon running a full installation or cleaning up.  That way, we can eliminate certain side effects of  these files lying around after a previous build.

My motivation is my previous PR about updating pdfjs, because even after changing back to my master branch (with an older pdfjs), npm installed the newer version.

and well, also install.py, that's what kucalc uses

# Testing Steps
There isn't much to test, because the overall install behavior just getting closer to a "fresh" install

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by williamstein** [comment]
Cool -- I'm glad you were able to track down what was causing confusion before.  What's the issue with pdfjs, btw?

**Comment by williamstein** [comment]
There is a script in src/scripts to ignore all package-lock files, which I wrote.  This approach `git ls-files '*/package-lock.json' | xargs rm -f` would be way better than what I did.

**Comment by haraldschilly** [comment]
There is no specific issue with pdfjs. It's just one of those packages which has a newer stable release, [list of fixes and improvements](https://github.com/mozilla/pdf.js/releases/tag/v2.0.943)

my only issue was after going back to master, to properly downgrade that library to where it was before

**Comment by haraldschilly** [comment]
> There is a script in src/scripts to ignore all package-lock files ...

Yes, I'm ignoring them as well, and don't notice them. That removal bash code still deletes them, i.e. what I want to say is that masking doesn't impact that git file search.

**Pull request merged**
