### PR TITLE
sagews: sage 9.0 / python3 compatibility

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
This is for making `smc_sagews` compatible with Python 2&3 (Sage 9.0).

My strategy is:
1. make this work with sage 9 / py3 – but be intelligent to not break too much, aim for dual compatibility
2. once it works, fix sage 8.9 running py2. having a diff of all changes at hand here will help to iron out the remaining problems.
3. of course, check again for sage 9

# Testing Steps
1.
1.
1.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Run eslint on new and edited files
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by haraldschilly** [comment]
Is there somewhere a documentation of that client/server protocol? So far, I got this far:

```
[...]
53129 (2019-12-27 13:09:29.580): Accepted a connection from ('127.0.0.1', 32798)
53129 (2019-12-27 13:09:29.589): forked off child with pid 53178 to handle this connection
53178 (2019-12-27 13:09:29.589): child process, will now serve this new connection
53178 (2019-12-27 13:09:29.590): Serving a connection
53178 (2019-12-27 13:09:29.591): Waiting for client to unlock the connection...
53178 (2019-12-27 13:09:29.592): Connection unlocked.
53178 (2019-12-27 13:09:29.635): Error receiving message: unknown message type '106' (connection terminated)
53178 (2019-12-27 13:09:29.635): Error taking connection:  unknown message type '106'
Traceback (most recent call last):
  File "/home/user/cocalc/src/smc_sagews/smc_sagews/sage_server.py", line 2225, in serve
    serve_connection(conn)
  File "/home/user/cocalc/src/smc_sagews/smc_sagews/sage_server.py", line 2031, in serve_connection
    typ, mesg = conn.recv()
  File "/home/user/cocalc/src/smc_sagews/smc_sagews/sage_server.py", line 234, in recv
    raise ValueError("unknown message type '%s'" % s[0])
ValueError: unknown message type '106'
53178 (2019-12-27 13:09:29.637): closing socket
53129 (2019-12-27 13:09:34.591): subprocess 53178 terminated, closing connection
```

i.e. the connection (with those tokens) is unlocked, but what's `106` ? Some overview might help.

**Comment by fchapoton** [comment]
Useful tool to hint for python3-bad code : "pylint --py3k"

**Comment by haraldschilly** [comment]
@fchapoton yes, thank you, this will be helpful :-)

**Comment by haraldschilly** [comment]
status: with the most recent commit I can eval cells, but features beyond that do not work (e.g. plotting or introspection). 

e.g. `ERROR -- exception raised 'No module named 'exceptions'' when executing 'EllipticCurve('420a').plot()`

but hey, at least some basics work:

Screenshot from 2020-01-02 17-04-01

**Comment by haraldschilly** [comment]
FTW :fireworks: 

Screenshot from 2020-01-02 18-23-35

**Comment by haraldschilly** [comment]
Screenshot from 2020-01-03 15-56-55

**Comment by DrXyzzy** [comment]
Testing started. **1. error with compute cell that only contains `%display latex`:**
```
Traceback (most recent call last):
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_server.py\", line 1218, in execute
    flags=compile_flags), namespace, locals)
  File \"\", line 1, in <module>
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_server.py\", line 1285, in execute_with_code_decorators
    for code_decorator in code_decorators
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_server.py\", line 1285, in <listcomp>
    for code_decorator in code_decorators
  File \"<string>\", line 1, in <module>
NameError: name 'display' is not defined
```

**Comment by DrXyzzy** [comment]
**2 When sage_server starts, it issues the following two warnings:**

This might be an old bug that python 3 is just now flagging. 
```
/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_jupyter.py:281: DeprecationWarning: invalid escape sequence \w
  if re.match('<IPython.core.display.\w+ object>'

/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_jupyter.py:307: DeprecationWarning: invalid escape sequence \W
  '^[^#]*\W?input\(', ccode):
```

**Comment by haraldschilly** [comment]
I think I addressed your second point in 34d66e9

**Comment by williamstein** [comment]
I just skimmed all the changes and they look good at a first glance.  Wow, this must have been a lot of work!

**Comment by DrXyzzy** [comment]
**3. octave plot in jupyter bridge fails**
(works with sage-8.9 and python2 sagews)
```
%octave
x = -10:0.1:10;plot (x, sin (x));
  ==>
Traceback (most recent call last):
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_server.py\", line 1218, in execute
    flags=compile_flags), namespace, locals)
  File \"\", line 1, in <module>
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_server.py\", line 1308, in execute_with_code_decorators
    code = code_decorator(code)
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_salvus.py\", line 2352, in octave
    return octave.jupyter_kernel(code, **kwargs)
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_jupyter.py\", line 356, in run_code
    display_mime(content['data'])
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_jupyter.py\", line 266, in display_mime
    show_plot(data, 'png')
  File \"/home/user/.local/lib/python3.6/site-packages/smc_sagews/sage_jupyter.py\", line 235, in show_plot
    fo.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by williamstein** [comment]
> TypeError: write() argument must be str, not bytes

and that exactly looks like a python2 vs python3 issue.

**Comment by haraldschilly** [comment]
@DrXyzzy I've committed afe08028056 which might address this. I haven't checked.

**Comment by DrXyzzy** [comment]
Yes, latest commit fixes reported issue #3 above.

- All tests in `src/smc_sagews/smc_sagews/tests/test_00_timing.py` and `test_graphics.py` now work when run manually.
- All tests in `test_doctests.py` work when launched with `sage -python3 -m pytest test_doctests.py`.

Also I didn't report before but the warnings in #2 about "DeprecationWarning: invalid escape sequence..." on `sage_server` start are gone with commit after that report.

I'm continuing working through the pytest suite for sagews.

**Comment by DrXyzzy** [comment]
**4. typeset_mode(True) causes error with sage-8.9**
Verify with `banner()` that sage-8.9 is running. See the following:
```
typeset_mode(True)
pi
  ==>
Error in lines 1-1
Traceback (most recent call last):
  File "smc_sagews/sage_server.py", line 1218, in execute
    flags=compile_flags), namespace, locals)
  File "", line 1, in <module>
  File "smc_sagews/sage_salvus.py", line 4050, in f
    show(obj, display=display)
  File "smc_sagews/sage_salvus.py", line 2878, in show
    from . import graphics
ImportError: cannot import name graphics
```
Output renders correctly when line ~ 2875 change is reverted from `from . import graphics` to `import graphics`.

**Comment by DrXyzzy** [comment]
## sage-8.9 test summary

I ran the hyperbolic plane sagews and all 176 or so pytests using the patch for this PR and sage worksheets with sage-8.9. The only issue I saw was #4 above, error on showing output with `typeset_mode(True)` in effect.

I'm going to resume testing sagews with sage-9.0.

**Comment by haraldschilly** [comment]
I'll look into this soon.

**Comment by haraldschilly** [comment]
Ok, I think 2683e4604cc984 fixes this. It's just changing such a discouraged relative import to an absolute one. However, I don't understand why it fails and there are similar imports which seem to work. Weird…

I also wasn't sure how to test, but I think you implied to first run `typeset_mode(True)` and then e.g. `1/123`

**Comment by DrXyzzy** [comment]
Looks good. Output after `typeset_mode(True)` is now rendered correctly with sage-8.9. I tested in a single cell and ran the entire hyperbolic plane worksheet.

**Comment by williamstein** [comment]
OK, merged.

**Comment by DrXyzzy** [comment]
I haven't finished testing with sage-9.0.

**Comment by williamstein** [comment]
> I haven't finished testing with sage-9.0

I think it is safe to merge now that it is tested with sage-8.9, since people would have to put in major effort to use it with 9.0.

**Comment by DrXyzzy** [comment]
Ok. It will be easier to continue testing without having to manage the patch branch when starting sage server and pytest framework.

**Comment by williamstein** [comment]
**Important:** This is merged into master since it seems to work.  However, I have personally observed, and at least one user quickly complained, that some Sage worksheets get stuck in a state where they refuse to start after making this live.  Thus right now (though in master) this is not live.  This will need to get resolved ASAP (e.g., on Monday) or I might have to do a huge revert commit, which sucks.  

Any ideas about why things could get stuck with this change?   I witnessed the problem with both sage-8.9 and sage-9.0, incidentally.

**Pull request merged**
