### PR TITLE
webapp/project: calculate a "slowdown" estimate depending on quotas.core and normalized load 5

### PR DESCRIPTION
**Pull request by haraldschilly**
The purpose of this is to make "free users" aware of the current load and the impact on running any calculations. It shows an estimate about how much longer a computation takes compared to having no elevated load or cpu core limits.

The problem is, I'm sure what I coded is at the wrong spot and can be done much better. I think what I wrote is at least safe to do.

I've assigned j3 because I think he knows exactly how to properly trigger this upon project startup.

### CODE REVIEW

**Comment by johnjeng** [comment]
UI and display logic tested. Did not test correctness of the `exec` calls.

**Comment by johnjeng** [comment]
I like that it's a positive statement. I guess there are no minimums? My bs meter always goes off whenever I read "up to X% faster". It's like when cable companies say you're paying for "up to X mbps".

**Comment by williamstein** [comment]
@johnjeng -- is this ready to go?  If not, can the label be changed to "needs work"...?

**Comment by johnjeng** [comment]
Yeah, I think this is good to go.

**Pull request merged**
