### PR TITLE
webapp/x11: add cadabra2

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

# Testing Steps
1.
1.
1.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by johnjeng** [comment]
This is not working for me. The button doesn't seem to do anything.

**Comment by johnjeng** [comment]
This is still failing for me.

**Comment by haraldschilly** [comment]
ok, I'll look into this

**Comment by haraldschilly** [comment]
stupid mistakes happen when it wasn't installed for testing. now it works!

**Pull request merged**
