### PR TITLE
update assistant 

### PR DESCRIPTION
**Pull request by haraldschilly**
pushes the reference to https://github.com/sagemathinc/cocalc-assistant/commit/0b36183f03a231809af0d40cda61450f8d168b69

# Description
this contains python2 → python3 updates

# Testing Steps
1.
1.
1.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by williamstein** [comment]
I don't know how to review or release this.    Why isn't the assistant just a subdirectory in the cocalc repo, or a completely separate repo + npm package?

**Comment by williamstein** [comment]
And why doesn't our build just grab master from the assistant repo?  

What's dangerous about this (you marked it "dangerous")?

**Comment by haraldschilly** [comment]
> I don't know how to review or release this. Why isn't the assistant just a subdirectory in the cocalc repo,

To make external contributions easier

>  or a completely separate repo + npm package?

It's a different repository. I don't know how to make npm packages.

**Comment by haraldschilly** [comment]
> And why doesn't our build just grab master from the assistant repo?

In case something is merged that causes problems, there is no control and the build suddenly breaks. The other way to do this would be tags with release numbers.

> 
> What's dangerous about this (you marked it "dangerous")?

It contains python2 → python3 updates of the code compiling the examples. They're supposed to be backwards compatible, but they're not tested in kucalc.

**Comment by haraldschilly** [comment]
To test this, I deployed it in "test". There were no problems.

I was also able to confirm that [this change to julia](https://github.com/sagemathinc/cocalc-assistant/compare/805f5699e16698a649a3929a2e8c83401edad0d0...0b36183f03a231809af0d40cda61450f8d168b69#diff-9124a12c399e7a3f99a9e1e5a859fc01R29) shows up

Screenshot from 2019-05-09 15-12-01

**Pull request merged**
