### PR TITLE
New Sync TS rewrite

### PR DESCRIPTION
**Pull request by haraldschilly**
**DON'T MERGE THIS (blindly)** This PR was made to trigger travis-ci for testing,  that's all.

# Testing Steps
1. travis-ci runs the specific sync test in utils

### CODE REVIEW

**Comment by williamstein** [comment]
> DON'T MERGE THIS (blindly) 

That would be pretty funny...

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging c4b8368eff6d02715e3d3726e6f8df622559f06d into 131b3db410832782829135ceee0c99aec24655af - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-4ca36bc011ae9620bd24bc984c30cbbe9865392c)

**new alerts:**

* 5 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 13 alerts** and **fixes 3** when merging 5f38f0c9fc729693303d57974724f59cda117a19 into 131b3db410832782829135ceee0c99aec24655af - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-d52f0d7cd846fae81ca2ce2115efcd6f84daeddb)

**new alerts:**

* 6 for Unreachable statement
* 5 for Ineffective parameter type
* 1 for Expression has no effect
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 11 alerts** and **fixes 3** when merging eb99b1f68901ac2fcf78a13427bed5db0903b29e into 131b3db410832782829135ceee0c99aec24655af - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-a69a3bfc836b8b922cfaae1c5038bb4b27fa2499)

**new alerts:**

* 5 for Unreachable statement
* 5 for Ineffective parameter type
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
good, the sync tests run in travis after my  commit edd44e1:

screenshot from 2019-01-08 11-57-48

**Comment by haraldschilly** [comment]
This pull request **introduces 11 alerts** and **fixes 3** when merging edd44e1ffc697f6a8650e5e505aaf6b4813c09d4 into 131b3db410832782829135ceee0c99aec24655af - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-1614a87f3f93db4ae534d485c629a02b8f26d7fd)

**new alerts:**

* 5 for Unreachable statement
* 5 for Ineffective parameter type
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging 7c379e9d197781fc994641d02085d2536c599c1a into 8ce83a8be8eae352b3be2a8592c9952d5fa7b064 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-668f6184a81deb708af57417b559074fa7437b25)

**new alerts:**

* 5 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging 6bd27cc8d7ca52464901a03eae12333741c9bc1e into 8ce83a8be8eae352b3be2a8592c9952d5fa7b064 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-8831f8f6332c865da33b01d6a6385d60bb510877)

**new alerts:**

* 5 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging d381f8478de1f5a0c75982415417eb2839274a66 into 8ce83a8be8eae352b3be2a8592c9952d5fa7b064 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-40e631cffbe81c14b838668f8299e5479fcfefd2)

**new alerts:**

* 5 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging cf92aa54de9d98c869852158339809fb5138ec1c into 8ce83a8be8eae352b3be2a8592c9952d5fa7b064 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-9770b11f86b1f8621bb8dd8cdb225504ae5498fa)

**new alerts:**

* 5 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging 4f26bdb5c7333ef53add9a422462afcbcc7e81d2 into 8ce83a8be8eae352b3be2a8592c9952d5fa7b064 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-7c52d05cd82debe740331b54b3c3c448d50b86f0)

**new alerts:**

* 5 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging 0542007fa891fd11f43c4a0904fa94b5bf31de2a into 8ce83a8be8eae352b3be2a8592c9952d5fa7b064 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-ea983612bc43a8157b2593a95d9269c4651c3966)

**new alerts:**

* 5 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging 4e5236e1f94c0714e60e14b590b3d65fe690bfa1 into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-aa46bb425fbc5965a616b0ae0c2ae6b1464d855d)

**new alerts:**

* 6 for Ineffective parameter type
* 3 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 11 alerts** and **fixes 3** when merging 70e15472ae43a37b24d0ef3c7e33b1ab02d70a3a into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-03d5b7d6d4dbbf82da2d743a880086bee9da8258)

**new alerts:**

* 6 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 11 alerts** and **fixes 3** when merging c8d245af8c90c456e787767f46435670cd24296c into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-b85603d68824f22f033bb817a505243958d20a66)

**new alerts:**

* 6 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 11 alerts** and **fixes 3** when merging 7d0bd0c9aabf8652b1c4eb8839737b6fd01ff972 into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-e8d4ea3e517387e8bf658a1e09d6b7260368460e)

**new alerts:**

* 6 for Ineffective parameter type
* 4 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging 81bebdfef2e5f6e14230986974abd5294b30a524 into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-2002dbf49f10728c6717fa014e9375ff79539a5f)

**new alerts:**

* 6 for Ineffective parameter type
* 3 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging 8c07629e8f6d2ceb83274f867d432ec2380e832f into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-9fa228040e100e2658dfd340759704594f0c35fe)

**new alerts:**

* 6 for Ineffective parameter type
* 3 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 10 alerts** and **fixes 3** when merging 7b32061827591c5305f95f44bbe93ec0e59503db into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-4b9e1263782284b0aa28bfb49590236b0a8820ca)

**new alerts:**

* 6 for Ineffective parameter type
* 3 for Unreachable statement
* 1 for Overwritten property

**fixed alerts:**

* 2 for Self assignment
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
