### PR TITLE
Course grading dialog

### PR DESCRIPTION
**Pull request by haraldschilly**
First step towards "assisted" grading. The most fundamental idea is to assign points to files (later, also automatically via some magic™) . Everything syncs as usual, which is pretty neat.

The most important aspect to review is the structure of the course file. It's modeled closely how grades are done. But additionally, there is a mapping from each file path in the collected files of the respective student to an integer (the points), and defaults to zero → see `course/actions::set_points`.

### CODE REVIEW

**Comment by johnjeng** [comment]
Should this be labeled `Needs review`?

**Comment by johnjeng** [comment]
I know I'm supposed to review it this week. Should I do that now or later?

**Comment by williamstein** [comment]
Can you add a few screen shots.  Jayadev was asking about something *like this*, but we can't tell, since we don't know what this looks like, and I can barely remember...

**Comment by haraldschilly** [comment]
Here are some screenshots. First, it shows the two grading modes in the configuration, then the general editor  with some annotations, and examples for the different states and also a discussion about a student assignment. 

## Configuration

grading-config

Point mode: remember, the total number is **16 points**, will appear again in some screenshots.

grading-config-2

## Editor and manual grading

grading-manual-1

## Discussion

grading-manual-discussion


##  the grading column in the overview of all assignments (points mode)

grading-manual-points-overview

## unconfirmed points mode

grading-manual-points-unconfirmed

## confirmed

grading-manual-points-confirmed

**Comment by johnjeng** [comment]
Okay, I've merged the with master. The new files are still all in coffeescript though. Everything else has been converted to the respective TS files. There are still some errors but they should be easy to fix.

Let me know if you run into any more troubles.

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging c1d943d54cfecaa1d7fb9fd9118e24311bf49b43 into 0d35f5f67de5bb9cad5e64c9db9011a4bb949c73 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-d3f077bcbd56754696c10fb6b4495f929ca65e04)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging a1d287791690fe096f9dc55ef7808f9e040f9ada into bffc1c243abb57b142e5158ecb2354ae760b3de7 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-cf776fd01b49a8afdfa7600726cd9f383985af30)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 5327d922da5327e90b1de51a1167be9f7e85e00a into cd4c62fcc7640931a95458c1db8dad11b8369c9d - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-2c2d875c2ba3e1196b3c2f0e563a9f14e9417830)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 8142ebed2a117ade2f28a8163229c5a5df58b066 into 131b3db410832782829135ceee0c99aec24655af - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-249493a69603bb3ac779f68e9aba5109d847278b)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging cae8df23f0ff21c0a2e41c20438b25b10ea74991 into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-57792b25cc1302c138b1fc1723d69c9019fc548f)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 4622c7219bcbe0eebe25332a8c37e3d38a4a514d into 98bd0518464576000dc1ab95ab884718b5e76a2e - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-ad50e3539fdea0479d86c69c61287b86d4fb66f6)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 0185e20ad7e3a1facc7824191fd54690a5eeea88 into e43d2f9667d6df4be9b22b7c66eb55fec123f0b6 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-53b4e792dab260a1a37b7c1259894224bc2506e8)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
need help: how do the cursors work? I get this exception:

```
Uncaught TypeError: Cannot read property 'get' of null
    at eval (actions.ts?80f5:357)
    at List.__iterate (immutable.js?bfba:2206)
    at List.forEach (immutable.js?bfba:4381)
    at eval (actions.ts?80f5:356)
    at eval (immutable.js?bfba:1377)
    at ArrayMapNode.iterate.HashCollisionNode.iterate (immutable.js?bfba:1726)
    at Map.__iterate (immutable.js?bfba:1375)
    at Map.forEach (immutable.js?bfba:4381)
    at SyncDB.CourseActions._this._syncdb_cursor_activity (actions.ts?80f5:355)
    at SyncDB.EventEmitter.emit (events.js?faa1:81)
```

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 86f1e8fa8827554e1d5622d8a3864844903227aa into 259afc6d933543531c7e7551864b5b78fb119c5f - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-d8dd7fbe40c0b721990c1e3443d1853b9ba6f365)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 5c5400b9c795515adace991361b9e8f824142008 into ddf35db5ce4911d54bc323b7e6d4afee349c6ad3 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-737707d63161cff67b6600703ec195a7dc1283c3)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging f3c81d0e6759d7b8117e1ab66724ec11bbef3f8d into e4b479049efaaf4c3cd0f0282665cb90d4b8f4a5 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-2325315d5bef8a99514b995645288e65d4c9d335)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 6e20468af64d1eac1d2d05a9aedb552b1deb92b8 into 61a36b32a89b9ed19fb8dba7cafc870b811c86d3 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-7e6f768f0f78da376ed5717ebe0995fce7028859)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
another issue where I need help: there are calls to `actions.set_grade` and `actions.set_comments`, but they no longer exist. how did they get replaced? looks like this is called "feedback" now, but I don't understand how I can set this with what's in the actions class. is this somewhere documented?

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging a1d2738030ab8a2ab4e7e08abd4f375d3d11d46d into ea121b4dbe522026b7b6c54718be19e843b2b6b7 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-e04295a08f40fc11c0f2c2fbdbb2a2b557ce5230)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging a91357acdaef88c9db3afc305272336d1fdd7a15 into ea121b4dbe522026b7b6c54718be19e843b2b6b7 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-692399619d880495f604725df3d8bb5a3427f92b)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 9b504e4bfb4d5406cb204066c7c3d7a3c3cefc60 into 5fbcfd083dead03784886392a9cb0cf0d0d672c0 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-19f86a83492521c1b201f3225bfdfe37e99358af)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
how are tables initialized? now I get 

```
synctable.ts?d759:214 Uncaught (in promise) Error: table not yet initialized
    at SyncTable.get (synctable.ts?d759:214)
    at ProjectsActions.have_project (projects.cjsx?21a0:104)
    at ProjectsActions.set_project_title (projects.cjsx?21a0:107)
    at CourseActions.configure_project_title (actions.ts?80f5:1186)
    at CourseActions.configure_project (actions.ts?80f5:1376)
    at CourseActions.configure_all_projects (actions.ts?80f5:1425)
    at Object.cb (sync.ts?23ff:113)
    at ProjectsStore.Store.wait (Store.ts?dbb2:160)
    at SyncDB.eval (sync.ts?23ff:103)
    at Object.onceWrapper (events.js?faa1:238)
```

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 5b88002b3db5bad115bcc6cf5d23fe17ef4d9f3e into 0f494c981e1833d78f31de94cbdc0a04d240c799 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-b5486ea2badadbe9535c1875f9700e86569265ec)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 9f6bd79f5bea4be9a3de6d4a990c118faaedcf77 into b7e0208b734349a0f48b13ee9798caa090ed2c90 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-0c98ffcdd4ac8b23eb6f63352ca35a23e97f422b)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 82010840cf7ac383efc394de125e2f64ac5f57ec into b0df27e99b5081b270a4c40aafbcb775d3ee0f5b - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-ad041c9ed7c5ab9057e4f39a3596df367e0f3f50)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 9c886c890d6e5053dcfc3b3224d0454cf772487d into a83a37f45c47bb4c22939e6a834e96242565bd55 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-b3daea13dfa6ef246bc28a09ed0ce5a262b0ec72)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging b47aed4060e9d63e09724e72035f4423c40d2c42 into d412a05c9453cd5c3271b4a518deb1da7510d84f - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-2cba985a11829308de509ca2fcb253f91ba3e922)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging 10e17a0c87d76b9b52accac467d0b0037b6e78b0 into 1a1f0261629ac02c84af36cee1d99e13a8f0d0a8 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-3740a7eee2303c57f07d4354bee53805c495a336)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging ed37543bbd46af7ad6edd136c3a2cb04928a9a78 into 0a3e65531257d06360217fa4df1c78fd83cbf543 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-0bff2c5581ed74587baeeb0a71eb8a8665b4030b)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging 9ab9d95cf44af1e5490293470dba7e2fa7437fc1 into 4444232e3251b16ccee70a96e4d506e055487451 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-fafeaead8ba5b8782929f73bacf6aad81ee615ae)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging 3be660c9e279a05d9b8345faecd9218676a3c3f7 into 4444232e3251b16ccee70a96e4d506e055487451 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-a95edf9f52b59d71828cbcfbae73e59bf2a5d9e8)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging 032851640f5df1aa4a273390e169a8e0493f9597 into 035e22b92bad320e904ee5d990bc8a6a365cf2e8 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-ea2f354e0b53e07163e43aeb9c0e5daf116ee56d)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging d73fdbbd4149300f6593c89104ab046b1d53f442 into 7bb5050da3965da048de682f2461add67ef52ea5 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-c3e83805b6a13878932390675204dcd7d9e45093)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging ab4f1d2855f6a4278eac53578cfca2b9cad4422a into 9f47e008c3503849a31490e9bbf790c04d829211 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-872066cf7142e47a02e51d4791c485d21aee62c0)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging 9c2f2dd11cddeccfc3f764a0097356ec78246ccf into 20c68473e5b6605984e669ff117751aa9be1e2a1 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-3f90f92721a6ff57d6e31d37e24c35bd7112f8de)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging d312749749f4f4741e8b7b71665e2fa43e9f5125 into 02bfc1e7041ca2d9f19950c10ad37a6d3003b1f5 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-6ac7d18b617080ed1a82adf2c9a70556472193d7)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging 640a300e19ca38ee4b717286d7df09b998adcc2e into d989b5823b0f2ace0f04c4d912505e23cf719b02 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-9f55ae74ca9039b3e84976ba96a47599ef196c26)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 14 alerts** when merging 27fd758dbfd7b4c4f1a24d4741db21e88cbaa439 into 077c2c6184fe28b5d325c032976b2fc8a997fc00 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-7e9b770fd27dec1f04980a7f825628b1e46503a5)

**new alerts:**

* 11 for Useless assignment to local variable
* 1 for Unreachable statement
* 1 for Useless conditional
* 1 for Unbound event handler receiver

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging fcb3d5217648248086da9bd7b1e4b0079e427338 into 077c2c6184fe28b5d325c032976b2fc8a997fc00 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-af6d2393f946b520d80ac4799bcc6252809b2dba)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 3d5c086501bd23b2f83db1d77f2985757a7080a4 into a4304fe05029fe03e0a32de1bf7d810f3190d785 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-73d4a7ff7f86ce141abfd89cb009732690ed549e)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by williamstein** [comment]
Closing due to being stale for long, merge conflicts, and probably something more tightly integrated with courses and annotation may be better.

**Pull request closed without merging**
