### PR TITLE
webapp: various smc → cocalc renamings and licensing code

### PR DESCRIPTION
**Pull request by haraldschilly**
issue #2111

process: replacing text and comments

time: 15 min

### CODE REVIEW

**Comment by DrXyzzy** [comment]
first pass review, looks as if the 5 instances of boilerplate:
```
#    This program is distributed in the hope that it will be useful,
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
```
are missing a line. Correct text is visible at [src/misc.py](https://github.com/sagemathinc/cocalc/blob/master/src/misc.py):
```
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
```

**Comment by haraldschilly** [comment]
Oh, well, don't bother with the licensing text. They are probably GPL2+ artefacts. At some point I'll use some off-the-shelf script or come up with something on my own to fix all of them.

**Comment by haraldschilly** [comment]
and actually, both are wrong. See https://www.gnu.org/licenses/agpl-3.0.en.html at the bottom.

We deliberately have a mix of licenses, so it's not always clear what's going on. Maybe we should start a dedicated licensing issue and classify our files first.

**Comment by williamstein** [comment]
Irregardless of what FSF says, we should just have a single one-line statement in every file, which explicitly refers to another file, which has the canonical correct statement.  Doing anything else is madness.

**Pull request merged**
