### PR TITLE
webapp: let copy operation write to clipboard (if allowed)

### PR DESCRIPTION
**Pull request by haraldschilly**
adding this line here, because it's quite odd to me to not write to the clipboard

### CODE REVIEW

**Comment by williamstein** [comment]
I only didn't do this, since I didn't know how.

**Comment by williamstein** [comment]
I merged this since I don't think it is wrong to do.  However, is there any context in which it would actually work???

**Comment by williamstein** [comment]
Of course this doesn't work....  That's why github has some funny flash button for copying the url of a git repo to the clipboard.  I think I've spent days in the past investigating this sort of thing...

**Comment by haraldschilly** [comment]
For me this works. I can select some text (e.g. in codemirror, or some sagews output text) and press copy. Then, in another application like a text editor, I can paste it.

Github shows you a flash icon? That's interesting. I have a normal svg icon and I think it uses the selection api to copy it. AFAIK, this only works for such selectable text boxes, though.

Here is a library generalizing all this https://github.com/zenorocha/clipboard.js/

**Comment by williamstein** [comment]
Maybe Macs are more locked down/secured for this particular thing (copy/paste).  In any case, if it works somewhere, I see no harm in including it.  Thanks!

– William

**Pull request merged**
