### PR TITLE
webapp/project files: library and +new

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
Reconcile +New contols in Files and fix some layout issues...

# Testing Steps
1. no files
    * create button → dialog
    * searching → create, also some buttons
1. there are files
    *  no search text, +create button
    * some other text in search → create file mode
1. editing the filename works, creating a file should show up with the indicated filetype
1. attempt to create a file without extension → error shows up. 
   *  similarly an error for  a stopped project. ← **that's no longer the case**. looks like this is also broken in production, though. this should be a follow up issue.
1. uploading 
   * by dropping onto existing files
   *  by dropping onto drop area in +create panel
   * in both cases the files listing updates 
1. actions that previously opened up +new should no longer do so (e.g. in jupyter menu, file → new)
1. library shows up and hides when clicking on close
1. grabbing a copy from the library works as usual, and the files listing switches to the target directory
1. settings panel boxes in project settings show up fine

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [x] Screenshots if relevant.

### basic layout 

screenshot from 2018-12-13 21-09-45

### create panel

screenshot from 2018-12-13 21-07-55

### no files, typing in search text

screenshot from 2018-12-13 21-11-14

### file action delete opened

screenshot from 2018-12-13 21-09-10

### library

screenshot from 2018-12-13 21-08-16

### terminal output
* also still scrollable, aligns on the right hand side, changed the clear button

screenshot from 2018-12-13 21-09-58

### placement of files button and dropdown changed slightly

screenshot-cocalc com-2018 12 13-21-11-53

### upload done + showing the uploaded file

screenshot from 2018-12-13 21-18-53

### CODE REVIEW

**Comment by johnjeng** [comment]
This has a failing build. Should I be testing it?

**Comment by haraldschilly** [comment]
> This has a failing build. Should I be testing it?

well, actually, the build works, but the tests fail. that's because I merged it after william's sync branch got merged, which introduces this. overall, I had no troubles merging any of my branches, hence I hope this is still ok. checking again isn't a bad idea :man_juggling:

**Comment by williamstein** [comment]
## A. It doesn't work for creating directories

The first thing I tried was "+Create" then `a/b/c/` and it failed in multiple ways:

1. It didn't create the directories.
2. The error is scrunched on the left (maybe OK), and there is ANOTHER error showing `{}` on the upper right (which means a mistake converting between object and string?).

Here are some screenshots.

screenshot 2019-01-25 at 11 35 22 am

screenshot 2019-01-25 at 11 35 40 am

## B. Make it easier to close

With the old +New, it is very easy to go away from the page or get rid of by clicking on any other tab.  With this new one you have to find and locate the x far away in the upper right or this big display that is completely hiding **your files that you desperately need** is there.  This could be really confusing for some poor people.  Can you test this UI on somebody by watching them use it?    If nothing else, can we make the +Create button itself toggle the dialog as well, or also add a close button at the bottom and/or top?  

My point is that on a smaller screen if you don't know to scroll down to your files, you could get really frustrated.  Of course, a frustrated user will probably refresh their browser at some point to get around this, but we don't want to frustrate people.

The current live Create dropdown *menu* (the caret thing) is fine, because you know how to close it -- just click it again. Let's make this dialog just as easy to close?

**Comment by haraldschilly** [comment]
Finally, I cracked  **A**, see:

```
~/projects/ae1d6165-1310-4949-b266-e0448fdd065f$ stat a
  File: a
  Size: 34086           Blocks: 10         IO Block: 34304  regular file
[...]

~/projects/ae1d6165-1310-4949-b266-e0448fdd065f$ head -1 a
2019-01-05T18:04:02.222Z - debug: primus-api request object [...]
```

I'll make a ticket with a reproducible case for this, rather than starting to fix this here.

**Pull request merged**
