### PR TITLE
webapp/billing: adding more details to the FAQ explaining aspects around project files and courses

### PR DESCRIPTION
**Pull request by haraldschilly**
(in particular around avoiding vendor lock-in)

### CODE REVIEW

**Comment by williamstein** [comment]
Text looks fine to me; if it works, feel free to merge and make live.

**Comment by DrXyzzy** [comment]
@haraldschilly, I reviewed the English and have no edits. However, I am seeing two defects in Firefox with cc-in-cc running the PR branch:
1. The entire __About__ section normally visible at bottom left of the Help page is missing.
1. The __Help__ button normally visible between settings/account name and notification bell at upper right is missing.

**Comment by haraldschilly** [comment]
@DrXyzzy strange, I just did a full rebuild and everything is in place. I'll merge it and do a test build for staging.

**Comment by DrXyzzy** [comment]
I did `npm run clean` and `npm run make` and saw the two problems mentioned above with Chrome and cc-in-cc. Oh well.

**Pull request merged**
