### PR TITLE
Wizard updates

### PR DESCRIPTION
**Pull request by haraldschilly**
besides more content, this is a rename to "examples" and it switches to use python 3. there shouldn't be any surprises...

### CODE REVIEW

**Comment by williamstein** [comment]
What should we do to review this?  What is the risk?

**Comment by haraldschilly** [comment]
The risk is that – after changing the directory name and switching to python3 – the webapp build process fails somewhere. It works in smc-in-smc for me and I don't see why it should fail, but in theory a surprise might be buried...

**Comment by slel** [comment]
Hold on, I think you wrote 'Exampples' (with double 'p') everywhere.

**Comment by williamstein** [comment]
This instantly fails to build in kucalc, and probably would fail in the same way on our live site.  We need to explicitly apt install maybe the python3-yaml package, since it isn't a default python package in ubuntu Docker...
```
$ c cocalc static init -t pr0 --commit=441a8bba7f51363adcf1067728ac9e86d0343fd5
...
Step 15/19 : RUN /build.py
 ---> Running in 64d2120473ee
RUN  git fetch --all
Fetching origin
From https://github.com/sagemathinc/cocalc
 * [new branch]      issue/2234 -> origin/issue/2234
 * [new branch]      issue/2245 -> origin/issue/2245
   579de2c..a55a285  kucalc     -> origin/kucalc
   49f24d3..428808a  master     -> origin/master
 * [new branch]      project-new-markdown -> origin/project-new-markdown
   f7f4363..99ea5cc  ssh-UI     -> origin/ssh-UI
   c983d86..441a8bb  wizard-updates -> origin/wizard-updates
RUN  git checkout 441a8bba7f51363adcf1067728ac9e86d0343fd5
Previous HEAD position was 49f24d3... Merge branch 'export_sagews2ipynb_button'
HEAD is now at 441a8bb... Merge branch 'master' into wizard-updates
RUN  source ./smc-env && CDN_BASE_URL="" python install.py webapp build
python3 build.py input ../webapp-lib/examples/examples.json
Traceback (most recent call last):
  File "build.py", line 25, in <module>
    import yaml
ImportError: No module named 'yaml'
```

I will fix this for the new kucalc2, but can you test/fix this for the current cocalc-webapp2 thing before it is merged?

**Comment by williamstein** [comment]
Actually, to avoid confusion I'll fix this everywhere.

**Comment by williamstein** [comment]
I get this error when running `w` to build in my project:
```
WARNING in ./smc-webapp/~/mocha/mocha.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source 
to get better results.
 @ ./smc-webapp/~/mocha/mocha.js 1:113-120
 
ERROR in ./smc-webapp/examples.cjsx
Module not found: Error: Cannot resolve module 'examples/examples.json' in /projects/45f4aab5-7698-4ac8-9f63-9fd307401ad7/smc/src/smc-weba
pp
 @ ./smc-webapp/examples.cjsx 147:17-50
Child html-webpack-plugin for "app.html":
        + 13 hidden modules
```

Maybe you forgot to include something in your commit. 

I also attempted to fix the Docker builds with one or two obvious changes and failed.

So todo for you: pull what I just pushed to this branch and from master for kucalc, then **TEST** this properly (e.g., in a clean smc-in-smc, etc.) and fix all the problems...

**Comment by haraldschilly** [comment]
Ok, oh I see, and is "w" this `npm run webpack-watch-map` ? That can't work out of the box and must be broken because the build failed.

**Comment by williamstein** [comment]
Yes, that's w.

**Comment by haraldschilly** [comment]
small status update: I've updated the webapp builder and successfully deployed a new build on https://test.cocalc.com/

**Comment by williamstein** [comment]
> small status update: I've updated the webapp builder and successfully deployed a new build on https://test.cocalc.com/ (and confirmed that the changes do show up)

OK, I'll merge this.

**Pull request merged**
