### PR TITLE
Typescript file listing

### PR DESCRIPTION
**Pull request by johnjeng**
# Description
Refactor and Typescript FileListing into its own module.

# Testing Steps
1. Checking items and performing actions on them still works
1. Highlighting text works
1. File download button works
1. ctrl/cmd open works
1. Opening folders works
1. Opening files works
1. Upload via drag and drop works

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [x] No debugging console.log messages.
- [x] All new code is actually used.
- [x] Non-obvious code has some sort of comments.

Front end:
- [x] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [x] Completely restart Webpack with `./w` in `/src`
- [x] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`

### CODE REVIEW

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 5c0a7853e6337cb61aec8b7e50db4d6741cde563 into 156004ad77a8029d157b32c19ac9c8978818bfc0 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-52447f0bbcd621656cb89ba17573251add90e479)

**new alerts:**

* 1 for Unreachable statement
* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by williamstein** [comment]
@johnjeng I see this in your code:
```
const { Row, Col } = require("react-bootstrap");
```
but we *do* have @types/react-bootstrap installed, so you should be able to import and get typings.

**Comment by williamstein** [comment]
I tried this in one file and it worked fine.  There are many to change, which I can leave to you for a tiny followup PR:

Screenshot 2019-03-15 at 8 10 27 AM

**Comment by williamstein** [comment]
file-listing.tsx has a block of decaf suggestions at the top, but I think you addressed them already?

**Pull request merged**
