### PR TITLE
hub/email: fix invite email sender config

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

* issue #5282
* issue #4881
* a missing callback when inviting someone (I generalized the code, though)
* fixing replyTo attribute for nodemailer (also, updated it)

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by haraldschilly** [comment]
so far, I only tested this in my dev project. we definitely have to double check in "test". its affecting course and project invite emails, especially with a custom smtp setup. deployment: hub, the part for "static" can wait.

**Comment by haraldschilly** [comment]
I've merged the #5303 into this one  here as well. Well, in any case, we should update the hub just once to get everything in.

**Comment by williamstein** [comment]
> we definitely have to double check in "test" – building now. 

And... did you test it there successfully?  Also, does this **require** updating the hub before building static, or are the frontend changes backward compatible with the non-updated hub?

**Comment by haraldschilly** [comment]
The webapp part is independent, it's kind of "cosmetic" only.

My tests in "test" were successful.

But, the most important change is for CoCalc instances on different domains! The reason is those "from name/from email" pairs were hardcoded. I either never realized that or just forgot implementing it. So, now, instead of `invites@cocalc.com` the sender will be the organization's email address from the site settings config. This is important, because otherwise emails sent from a different domain easily end up as spam, because the sender's domain doesn't match. However, the "reply to" is the email from the cocalc user, as usual.

**Pull request merged**
