### PR TITLE
Boost licenses backend

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

this implements all the special handling to process `{quota: {boost: true}}` licenses. I should deploy this in test to double check if it works – apart from that its done.

- built packages tagged `pr-5795` and deploying hub as `2022-04-05-142827-boost-pr-5795` 
- and manage: `2022-04-05-125142-boost-pr-5795`
- I tested this and found one final tricky bug. It runs fine in "test".

deployment:
- manage must be first, because the effective quota is calculated based on the licenses set in the hub (backwards compatible, of course)
- then at least the websocket hub, because that's where the "hook", for deciding which licenses to use, runs.

TODO:
- [ ] there is an inconsistency if there is no regular license at all
- [ ] figure out why hub crashes

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by haraldschilly** [comment]
very weird. I deployed this in "test" and well, it seems to work as expected … but some hubs crash. No idea how this happened.

```
2022-03-28T12:46:17.120Z: 2022-03-28T12:46:17.120Z cocalc:debug:postgres PostgreSQL._query('SELECT c.relname AS name FROM pg_class AS a
 JOIN pg_index AS b ON (a.oid = b.indrelid) JOIN pg_class AS c ON (c.oid = b.indexrelid)',id='8e6538'): "done (concurrent=0) (query_tim
e_ms=42) -- success"

2022-03-28T12:46:17.121Z: 2022-03-28T12:46:17.121Z cocalc:debug:postgres PostgreSQL._query('UPDATE server_settings',id='0e9e5d'): "quer
y='UPDATE server_settings SET \"readonly\"=$1 WHERE 1=1 (concurrent=1)'"

2022-03-28T12:46:17.125Z: 2022-03-28T12:46:17.125Z cocalc:debug:postgres PostgreSQL._query('UPDATE server_settings',id='0e9e5d'): "done
 (concurrent=0) (query_time_ms=4) -- success"

2022-03-28T12:46:17.126Z: 2022-03-28T12:46:17.126Z cocalc:info:hub Configure agent port

2022-03-28T12:46:17.126Z hub:healthcheck set_agent_endpoint 0.0.0.0:0
2022-03-28T12:46:17.126Z: 2022-03-28T12:46:17.126Z cocalc:info:hub initializing project control...

2022-03-28T12:46:17.127Z: 2022-03-28T12:46:17.127Z cocalc:debug:project-control init kucalc

2022-03-28T12:46:17.127Z: 2022-03-28T12:46:17.127Z cocalc:info:project-control creating project control client

2022-03-28T12:46:17.127Z: 2022-03-28T12:46:17.127Z cocalc:info:project-control project controller created with mode kucalc

Error: A metric with the name cocalc_database_query_queue_executed_total has already been registered.
    at Registry.registerMetric (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/registry.js:80:10)
    at new Metric (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/metric.js:48:13)
    at new Counter (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/counter.js:12:1)
    at Object.newCounter (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/server/node_modules/@cocalc/database/metrics.ts:13:
10)
    at Object.<anonymous> (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/server/node_modules/@cocalc/database/dist/postgres
-user-query-queue.js:49:30)
    at Object.<anonymous> (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/server/node_modules/@cocalc/database/dist/postgres
-user-query-queue.js:263:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-03-28T12:46:17.225Z: 2022-03-28T12:46:17.225Z cocalc:error:hub Error --  {}

RUN_HUB=/cocalc/bin/cocalc-hub-server
kubectl --namespace="test" -o json  get pods

**Comment by haraldschilly** [comment]
another oddity: license info says "exhausted" and `License can be used with up to 1 simultaneous running projects` ... but in the DB it clearly has `run_limit : 3` set. I did change the run limit (it was 1 initially), so, somehow this is cached.

**Comment by haraldschilly** [comment]
after deploying in test, what I actually tested: 1st screenshot the boost is not used, because the regular 2hour idle timeout licenses are active. the 2nd screenshot shows how it is active when compared properly. 3rd screenshot is just the boost and nothing else.

**Comment by haraldschilly** [comment]
well, I'm completely stuck with this. after going through more and more details without any idea, I finally had another thought to build from "master". I forked off at 0306be1c69 and well, my [changes are here](https://github.com/sagemathinc/cocalc/compare/upd-hub-db-test) … What I did in my dev project

```
npm run make
./workspaces.py update-version --packages database,util,hub --newversion minor
./workspaces.py publish --packages database,util,hub  --tag upd-hub-db-test
# that failed because of a duplicate version number. I almost didn't notice the error. In any case:
./workspaces.py update-version --packages database,util,hub --newversion patch
./workspaces.py publish --packages database,util,hub  --tag upd-hub-db-test
```
Checked at npmjs to have additional packages and well, then ran `co hub init -t now-upd-hub-db-test --npmtag upd-hub-db-test`

with that, I still end up with

```
2022-04-01T11:19:11.069Z: 2022-04-01T11:19:11.069Z cocalc:debug:project-control init kucalc

2022-04-01T11:19:11.069Z: 2022-04-01T11:19:11.069Z cocalc:info:project-control creating project control client

2022-04-01T11:19:11.069Z: 2022-04-01T11:19:11.069Z cocalc:info:project-control project controller created with mode kucalc

Error: A metric with the name cocalc_database_query_queue_executed_total has already been registered.
    at Registry.registerMetric (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/registry.js:80:10)
    at new Metric (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/metric.js:48:13)
    at new Counter (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/counter.js:12:1)
    at Object.newCounter (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/server/node_modules/@cocalc/database/metrics.ts:
13:10)
    at Object.<anonymous> (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/server/node_modules/@cocalc/database/dist/postg
res-user-query-queue.js:49:30)
    at Object.<anonymous> (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/server/node_modules/@cocalc/database/dist/postg
res-user-query-queue.js:263:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-04-01T11:19:11.188Z: 2022-04-01T11:19:11.188Z cocalc:error:hub Error --  {}

RUN_HUB=/cocalc/bin/cocalc-hub-server
```

hence my conclusion is that the problem is not related to my code. either I'm doing something wrong or somewhere I have a fundamental, very weird, problem.

**Comment by williamstein** [comment]
Just to clarify, your code appears to work perfectly in a dev server, but you can't deploy it to test.cocalc.com?

**Comment by williamstein** [comment]
We should probably implement a version of "deploy on kucalc" that just builds from a github branch directly, rather than using an npm package.  I think we could easily do that as an option, and it would be much better for situations like testing a different branch...

**Pull request merged**
