### PR TITLE
Type db schema

### PR DESCRIPTION
**Pull request by johnjeng**
# Description
Adds some type checking to db-schema to ensure that get/set fields are actually declared. Remaining rules options are a work in progress.

Uses a `create` function so that you don't have to type fields and the write the fields for the object again. There could be a better way to type it but no [real luck yet](https://stackoverflow.com/questions/57517135/can-i-dynamically-type-an-object-literals-keys-to-be-based-on-a-siblings-keys).

@williamstein Maybe pull and make some typos to check how the errors look to you?

# Testing Steps
1. No compile errors
1. Run the main site
1. Check that accounts work

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [x] No debugging console.log messages.
- [x] All new code is actually used.
- [x] Non-obvious code has some sort of comments.

Front end:
- [x] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [x] Completely restart Webpack with `./w` in `/src`
- [x] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`

### CODE REVIEW

**Comment by williamstein** [comment]
It definitely feels useful.  I'm very impressed that it is possible to declare what you did in Typescript so elegantly.

**Comment by williamstein** [comment]
If this works, I'm happy to merge it.

**Comment by johnjeng** [comment]
It works as far as I can tell.

**Comment by haraldschilly** [comment]
did you see the travis errors? e.g.

> `2019-08-20T07:08:17.815Z - debug: PostgreSQL.update_schema: "error creating tables -- TypeError: Cannot read property 'virtual' of undefined"`

and in a test suite for webapp are 34 failing.  master is fine, hence I'm quite sure this is caused by the code here

**Comment by johnjeng** [comment]
Oh, yup, this is broken.

**Comment by johnjeng** [comment]
API tests seem to fail on master and Travis checks so I assume those are known to be broken.

**Pull request merged**
