### PR TITLE
fixing imports

### PR DESCRIPTION
**Pull request by fchapoton**
* sha is deprecated in favour of hashlib
* socket was imported twice

# Description

# Testing Steps
1.
1.
1.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by haraldschilly** [comment]
This pull request **fixes 2 alerts** when merging 8828afcdd785b2dc7a7c9f16d5893abdfa9d5290 into c92884fb5662148a08649c2e18352c24a6f49b52 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-3f0b7e953cab4dd2a6ab3f1a492eaf086dd41577)

**fixed alerts:**

* 1 for Module is imported more than once
* 1 for Import of deprecated module

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
hmm, I'm wondering if this file is anywhere in use. Thank you for the changes, but maybe we should actually delete it?

**Comment by williamstein** [comment]
It is used everywhere except in our kubernetes deploy.

**Comment by williamstein** [comment]
@haraldschilly my comment above is completely wrong -- I thought we were talking about smc_compute.py, but upon looking at this code, it's src/misc.py.  You're 100% right -- that stuff is not used at all anymore, and admin.py isn't used anymore either. I'll delete it.

**Pull request merged**
