### PR TITLE
Issue/3083

### PR DESCRIPTION
**Pull request by tscholl2**
Fixes 3083

### CODE REVIEW

**Comment by williamstein** [comment]
But I can't test the code, since the assistant is broken in my master dev/review project... ?

**Comment by haraldschilly** [comment]
I'll test this. I'm wondering about adding a language and forgetting to update that dictionary. Is codemirror robust against an undefined language?

**Comment by williamstein** [comment]
> I'm wondering about adding a language and forgetting to update that dictionary.

I wonder too -- at least it should fail gracefully.  I'm OK with a fix for doing things right (we should just directly use file_associations right, rather than copy from it!) being in a follow-up PR, since having syntax highlighting only some of the time is OK.

**Comment by tscholl2** [comment]
You can comment out the line where it passes the language and find out. I believe because of:

https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/jupyter/codemirror-static.tsx#L83

It will render any new language with python syntax highlighting. This matches what I observed while developing.

**Comment by williamstein** [comment]
> with python syntax highlighting

OK, probably better than nothing.

**Pull request merged**
