### PR TITLE
Fix frame menu 4000

### LINKED ISSUE #4000: dropdown menu for Source, etc is not visible in default tex frame editor in ~~future versions of~~ Chrome
Seen on macOS 10.14.3.
Seen with:
* Google Chrome (Canary) 78.0.3875.0 (Official Build) canary (64-bit) 
* HeadlessChrome/77.0.3844.0 (comes with current puppeteer-1.19.0.tgz)

**NOT seen** with:
* Google Chrome (stable) Version 76.0.3809.100 (Official Build) (64-bit)

This may be of interest so that we can prevent breakage when Chrome is updated.

Current view, Chrome 76 (ok):

tex-menu-chrome-76

Future view, Chrome 77 and 78 (can't see pulldown menu without resizing):

tex-menu-chrome-78

### LINKED ISSUE #4064: file dropdown button in code editor does a line wrap
via CSS, prevent that triangle from doing a newline.

Screenshot from 2019-09-06 13-54-05

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
different approach to fix #4000 … there are some contradicting problems I can't solve across browsers. So, this here isn't perfect either, just a bit better.

bonus: fix #4064

# Testing Steps
I tested this on chrome 76 and 77 and firefox 69. 

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by williamstein** [comment]
1. Can you make a PR that doesn't have thousands of lines of package-lock.json changes?  This PR doesn't even involve packages.
2. Any summary of the contradicting problems, and what this PR breaks?   It's easier to review/merge something with known problems if you tell me what those problems are...

**Comment by williamstein** [comment]
(I just realized that this is not needs-review yet)

**Comment by haraldschilly** [comment]
I've removed the lockfile removal.

The contradictions are using `float:"right"` for the control panel and causing the latest problem in #4000 vs. the dropdown menus do not show up (either in the control bar or in the buttonbar)  if `z-index` is used to fix the overlap. Another issue was a missing background in the title and the connection information. Otherwise one can see through one div to the other one. A third issue is using the flex layout for the top bar, as `direction: column`. This becomes apparent when some of the flex related styles slightly change. That's why the title bar style got a `flex: 0 0 auto` to avoid expanding to 50% height.

As it is here right now, it addresses most of the issues, but for very narrow frames the control buttons start to disappear to the right. flex seems to have a limit how far it likes to shrink and my attempts tuning the settings didn't help. The alternative would be to make the control always show up, by aligning the content to the right (and not the left). but then the opposite happens and the button bar disappears to the left.  Well, technically this is still an improvement (given it doesn't break to hefty on that newer safari, which I haven't tried yet).

**Comment by williamstein** [comment]
> I've removed the lockfile removal.

I see what's going on too - i've just merged that other PR about that.

**Comment by haraldschilly** [comment]
I've made further changes, and well, this solves a couple of problems but it's not perfect. I'm for merging this and then making new issues to brainstorm ideas. The browsers I tested are chrome 77, firefox 69 and safari 12.1 via browserstack.

**Comment by williamstein** [comment]
Wow, this makes the most important thing way worse.  I have to rever this PR somehow. Look my fullscreen toggle button in the upper right of the left frame is just gone:

image

**Comment by williamstein** [comment]
OK, I've fixed things so the upper right control is always visible.  You might consider this breaking things though... 🤷‍♂

**Pull request merged**
