### PR TITLE
database/always_running: does not respect admin settings

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

pretty minimal, shouldn't impact the DB, since it is already indexed. looks like this case was not ported over? in any case, what's missing is updating the DB version, but I don't want to cause a merge conflict.

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by williamstein** [comment]
If we make this change, won't cocalc start all projects that have the always running admin setting checked, but are currently stopped?  You explicitly argued against doing precisely this, and we changed it so that such projects aren't started (which is why only the run_quota is is the current query).  I seems to me like this PR is exactly half breaking something that you wanted from long ago?

**Comment by haraldschilly** [comment]
oh wait, that's a good point. I certainly got confused by this when working on cocalc cloud, but I see the point. I should check the DB.

**Comment by haraldschilly** [comment]
ok, well, I get your point and this certainly has an effect, but I think it's fine. Unless I fundamentally miss something, for us here in production, there are zero projects that would be started. i.e. I checked via `select project_id, state ->> 'state', title from projects where settings ->> 'always_running' = '1';` (15 projects, all "ours", all are running). So, I'm ok with that change, it makes this setting consistent.

**Comment by williamstein** [comment]
In that case, i'll merge it.

**Pull request merged**
