### PR TITLE
webapp/latex: adding help tab

### PR DESCRIPTION
**Pull request by haraldschilly**
@DrXyzzy this is about documentation and fixing my language. It also addresses #1610 a little bit, at least I think so.

### CODE REVIEW

**Comment by DrXyzzy** [comment]
@haraldschilly I made some minor edits and pushed to this PR branch. Additional comments:

- maybe missing link at line 154 about inserting image: `Follow [these instructions]...`
- is the plan to put this under a button called `Help` at upper right? If so, that might make support conversations confusing because there is already a `Help` button in a higher level toolbar at upper right. Looks as if they will have different icons, but might also want different button label.

**Comment by williamstein** [comment]
> is the plan to put this under a button called Help at upper right?

No since the vast majority of our users (99.99% ?) would never want to see this...

**Comment by williamstein** [comment]
There's a link right now to the API docs from the "get an api key" part of account settings...

**Comment by haraldschilly** [comment]
> is the plan to put this under a button called Help at upper right?

This patch already integrates it into the UI, in the latex editor. It looks similar, but once you see it, it's clear because of the context where it is placed. 

You're also right about the missing link.

**Comment by haraldschilly** [comment]
@DrXyzzy I've fixed the link and merged with master, so, IMHO this is ready to go in. Maybe you want to add one or another paragraph with useful information? I don't even know if we have latex related information in our wiki. So, one remaining task could be to either copy over some of the important bits and pieces from the wiki or to link to some of them.

Otherwise, this is something we can do later, too.

**Pull request merged**
