### PR TITLE
next: custom 404 page

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

Screenshot from 2022-02-17 12-09-46

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by williamstein** [comment]
fyi - @haraldschilly you absolutely can't do getStaticProps for this page, because it depends on information only available at runtime (e.g., to render the header), and the point of getstaticprops is "if you export a function called getStaticProps (Static Site Generation) from a page, Next.js will pre-render this page at build time using the props returned by getStaticProps.".

**Comment by williamstein** [comment]
> yes, I know about data being stale, it's just that showing any recognizable info and a link back to the min page is IMHO still better than the blank page saying nothing useful. 

The way you've code this, it completely breaks building cocalc-docker, since it's not possible **at build time** to run the getStaticProps function at all.  This is a blocker that has to be fixed.

> I didn't want to spend time on some client side fetching and processing of data, that could be a new enhancement ticket of its own!?

No matter what this won't be client side.  it's always definitely going to be server side, like most of our pages (e.g, the landing page). That's what
```export async function getServerSideProps(context) {
  return await withCustomize({ context }, { name: true });
}
```
does.   Just change the code from getStaticProps to getServerSideProps so it isn't completely broken?

**Comment by haraldschilly** [comment]
meh, github just swallowed my reply. There is no `getServerSideProps`. next.js argues this might overwhelm the server if there are too many requests, security, blabla → https://nextjs.org/docs/messages/404-get-initial-props

With that "client side query" enhancement, what I mean is to `useEffect` a query our `customize` endpoint, get the `siteName` directly from there, etc. I didn't want to do this. So, with that, let's just go ahead and hardcode the name or leave it out.

**Comment by williamstein** [comment]
Showing a page with a custom server side headers is something we already do properly and have for a long time. Look at pages/index.tsx. Using useEffectis very much the wrong solution here, as it is much slower.   

I can take this over.

**Comment by williamstein** [comment]
I now see that 404 is a special case and getServerSide props is not allowed.

**Pull request merged**
