### PR TITLE
frontend/flyout: porting over the project homepage from #6804 

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

This ports over the project homepage from #6804. There are no other changes, hence this is only relevant for the `vertical_fixed_bar==flyout` mode.

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by williamstein** [comment]
What does this do?  Can you include a screenshot?  Is it bringing back the original homepage, which I think nobody uses or wants (?) or something else?

**Comment by haraldschilly** [comment]
In that vertical-tab mode with flyout only, the homepage looks like that right now. I don't like this, because it is quite chaotic.

2024 08 29-old-homepage

 This PR changes that homepage to look like the following. I like this much more, because it just mentions the project, shortcuts to common tasks like opening files or creating new ones, and the recent files. This was part of that PR #6804 back then. There is absolutely no change with anything else (I would like to, but this is not part of that PR).

2024 08 29-new-homepage

**Comment by williamstein** [comment]
@mforbes (and others) made a strong argument based on user testing that the "Home" button should just show the file explorer in the home directory.  We listened and made that change about 6 months ago and people like it.   I don't understand what this PR does.

**Comment by williamstein** [comment]
I misunderstood this. Now that I see it ONLY impacts the situation when:

image

and nothing else, and there is a good logical reason for this.

**Pull request merged**
