### PR TITLE
webapp/x11:  100, 125 and 150% and 200% zoom selections

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
This adds 4 zoom selections to the X11 bar, to make changing the magnification easier. E.g. on my display, I'm usually happy to switch to 1.25x and clicking many times on the +-zoom button isn't nice.

Took me hours to figure out how to make a dropdown and wrapping work. Also fixing https://github.com/sagemathinc/cocalc/issues/3419 with the same idea.

# Testing Steps
1. x11 zooming
2. PDF preview, latex editor, code, etc ... they do not show these three buttons, but the magnification glass buttons still work fine

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [x] Screenshots if relevant.

screenshot from 2018-12-17 14-02-11

### CODE REVIEW

**Comment by williamstein** [comment]
Could you please (1) make this a dropdown button (to avoid clutter and having a different UI than every other program for selecting DPI's/ZOOMs), and (2) include the four standard DPI scaling options?    The standards are easy to find via google, but are in table 2 [here](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dpi-related-apis-and-registry-settings):

screenshot 2018-12-13 at 7 43 17 am

**Comment by haraldschilly** [comment]
Well, I'm not sure what you mean by that DPI scaling option comment. I've added 200%, if that's what you mean.

**Comment by williamstein** [comment]
> I've added 200%, if that's what you mean.

It's good to add that.    For now with the dropdown and those settings, I'm fine with merging this (once it works of course).

That said, X11 scaling isn't totally simple.  There's several distinct numbers at play here:

- The DPI is that is set in the xpra server:  Applications get this when they are started, and it (hopefully) impacts their font size settings.   Some applications respect this nicely and some don't.
- The devicePixelRatio of the browser:  E.g., on a HiDPI or Retina display, this number might be 1.8 or 2 or something.  On my 1080p Chromebook right now it is 1.25.     In order for things to look clean, the canvas that the X11 window is rendered on is by default increased in size by a factor of devicePixelRatio, then scaled back down when displayed.
- The zoom factor.  This is what changes when the user clicks the +/- buttons, and is a function of the "font size".     When you change this you can make fonts look big even for applications that ignore the DPI setting of xpra.  However, those applications may look very pixelated and ugly on devices with a high devicePixelRatio.

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 03eb3d5c0ddf41c8c0b40110f42712df00123672 into 864135b0a9547a0baca11dc3d668bf156eb92003 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-f50c217f8a8e18771a0da127917b485b338d19d0)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
