### PR TITLE
add ts support to hub api mocha test

### PR DESCRIPTION
**Pull request by DrXyzzy**
# Description
Fixes error reported by @haraldschilly, `Error: Cannot find module './failing-to-save'`, for the case of `smc-hub$ npm run testapi`

Should not affect production. The only changes are to devDependencies and scripts in package.json and test timeouts in the hub api mocha suite.

# Testing Steps
1. Install this PR patch.
1. Restart project.
1. In one .term:
    ```     
    cd ~/cocalc/src
    . smc-env 
    npm run clean
    time npm run make
    # real    5m26.959s
    dev/project/start_postgres.py
    # leave server running in foreground
    ```
1. In another .term:
    ```
    cd ~/cocalc/src
    . smc-env
    . dev/project/postgres-env
    cd smc-hub
    time BAIL=-b npm run testapi 2>&1 | grep -v debug
    # 101 passing (55s)
    ../scripts/mocha_clean.sh
    ```

# Relevant Issues #2627

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [x] No debugging console.log messages.
- [x] All new code is actually used.
- [x] Non-obvious code has some sort of comments.

Front end: N/A
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by DrXyzzy** [comment]
- BAIL option is a convenience for the tester and can be omitted. Setting it in the invocation tells mocha to exit on the first failure
- .travis-test.sh updated and testapi [fails](https://travis-ci.org/sagemathinc/cocalc/jobs/467775152#L1649):
> error:   Forever cannot find process with index: /home/travis/build/sagemathinc/cocalc/src/smc-project/local_hub.coffee`

I'm reviewing it. @haraldschilly maybe that message means something obvious to you.

**Comment by haraldschilly** [comment]
well, that's unfortunate :-(

the first error I can see is `: /bin/sh: 1: smc-sage-server: not found`. which is sort of obvious, because there is no sage and so on. I thought the API test just calls to the hub? E.g. `testpg` runs fine and tests the database part ... and it just requires to have postgres running, which the travis setup script does in the beginning.

**Comment by DrXyzzy** [comment]
A few of the mocha tests for smc-hub pass travis. I suggest merging what works so far.

**Comment by DrXyzzy** [comment]
Issues remaining:
  - The copy between projects tests fails the first time after `npm run make` in dev project, not just with travis.
  - With some test(s), which are skipped in present PR, there is a travis error due to dependency on `smc-sage-server`. Yet none of the api tests explicitly uses sage.

**Comment by haraldschilly** [comment]
I see, [20 more tests](https://travis-ci.org/sagemathinc/cocalc/jobs/469481485#L1442) are run by this. Good!

**Pull request merged**
