### PR TITLE
Ts r misc

### PR DESCRIPTION
**Pull request by johnjeng**
# Description
Todo:
- [x] Testing for NumberInput
- [x] Testing for TextInput

Typescript
 - SimpleX
 - SkinnyError
 - ErrorDisplay
 - LabeledRow
 - NumberInput
 - TextInput
 - Spinner

Added some render tests and some interaction tests.

# Testing Steps
1. Check loading screens for our spinner
1. Try to use a bogus coupon (SimpleX, SkinnyError, ErrorDisplay)
1. View project settings (LabeledRow)
1. Change editor tab/fontsize/autosave settings (NumberInput)
1. Edit project description and title (TextInput) 

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [x] No debugging console.log messages.
- [x] All new code is actually used.
- [x] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [x] Completely restart Webpack with `./w` in `/src`
- [x] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [x] Screenshots if relevant.

### CODE REVIEW

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 889ded3c74b97eb62946715ef79a0127dffac94c into b0df27e99b5081b270a4c40aafbcb775d3ee0f5b - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-32bc637618dbc06a58e7ddac63599d5b4bca0c63)

**new alerts:**

* 1 for Potentially inconsistent state update

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging baea7de634c8e0609789b3ea1f9c9d0a308cfd76 into ff5c09921dd37838112343c6ea4e10bc21e17199 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-bb27dc0d645cb7db00044ff04b88234a6cebf2ec)

**new alerts:**

* 1 for Potentially inconsistent state update

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 74fd674184b5ffa528f9d08c56b3dbd03d6e4e9b into ff5c09921dd37838112343c6ea4e10bc21e17199 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-5f87aa47c6d3088423c1217ba29ad225350d2a86)

**new alerts:**

* 1 for Potentially inconsistent state update

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by williamstein** [comment]
I clicked on the Subscriptions/Upgrades tab and BOOM -- crashed the whole page and got a blank screen and traceback.  This is clearly due to a missing or wrong import (due to the error).  I was following your testing steps (to create a subscription with invalid coupon), and it blew up:

screenshot 2019-03-07 at 12 12 51 pm

**Comment by williamstein** [comment]
OK, now looks good.

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging bceeb78428ad5f8cc3b2da05ba08895f14037a3a into b0d3bb74e21e21c4b9b17767840c80d7b0a2c6e7 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-f72fdc00c86cc2672f804811dbd05a565799c3d1)

**new alerts:**

* 1 for Expression has no effect

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
