### PR TITLE
webapp: adding rel="noopener" to external links

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
Basically https://developers.google.com/web/tools/lighthouse/audits/noopener

# Testing Steps
* this should be pretty safe to merge

what I didn't think about when I made this needs review:
* shift-click an editor tab to open in a small window
* open video chat window (that should definitely run independent of cocalc)

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by haraldschilly** [comment]
This pull request **fixes 3 alerts** when merging dcfd6852f371974eeeea1dfe18d9f6a5ae3fbe4d into e43d2f9667d6df4be9b22b7c66eb55fec123f0b6 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-17a375ac072a2637ae4773687c7a5e553a50c7f6)

**fixed alerts:**

* 3 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **fixes 3 alerts** when merging fb2422e6b4b69f2f918c787b6d75f042a7711627 into e43d2f9667d6df4be9b22b7c66eb55fec123f0b6 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-1e88d029475c212bd2e9f3632d095bcc21548823)

**fixed alerts:**

* 3 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **fixes 3 alerts** when merging fb2422e6b4b69f2f918c787b6d75f042a7711627 into d2727595a024629e1638528683922eaa1cebac0d - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-2287dac4364fc1731d97280d48b6669da14ebc19)

**fixed alerts:**

* 3 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by williamstein** [comment]
I did the other popup stuff (video chat, etc.) which is in misc_page, and is equally as important.

**Pull request merged**
