### PR TITLE
npm: update langchain google for gemini pro 1.5

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

Trivial package update, should make it work.

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by williamstein** [comment]
This obviously doesn't change the list of available models:

image

and I don't see anything in admin settings related to Gemini versions specifically.  How does version 1.5 get enabled?

**Comment by haraldschilly** [comment]
Hmm, not sure what's going on. Is this in your dev project? 1.0 and 1.5 show up by default, unless models to be shown are selected explicitly. Here is a screenshot of chat in my dev project:

Screenshot from 2024-04-25 17-49-45

**Comment by williamstein** [comment]
On https://cocalc.com Gemini 1.5 is not user selectable or visible.  Why?

**Comment by haraldschilly** [comment]
OK. I figured it out. The websocket service sends the `/customize` endpoint and right now runs on f50a7f9d3a794124e0 which only marks gemini pro as a working option: https://github.com/sagemathinc/cocalc/blob/f50a7f9d3a794124e0b57afcc7bd9162ff64dd07/src/packages/util/db-schema/llm-utils.ts#L134 … therefore, the web client only gets a list of LLMs without it.

**Comment by williamstein** [comment]
OK, that clears everything up.  I'm glad I didn't make the latest master code live before this PR for hub-websocket :-)
l will later today though. 

Thanks!

**Pull request merged**
