### PR TITLE
use markdown it emoji for smilies

### PR DESCRIPTION
**Pull request by haraldschilly**
this fixes the situations outlined in #3043 … but it can't fix all our emojis, because some of our current ones contain markdown text indicators (underlines). I'm rather for removing what we have and switch to that library.

screenshot from 2018-08-03 23-11-57

### CODE REVIEW

**Comment by haraldschilly** [comment]
what's left is to do

- [ ] decide, if we run it for all markdown, or only the ones for chatting (which means to add a boolean parameter)
- [ ] enable more smilies [upstream shortcut.js file](https://github.com/markdown-it/markdown-it-emoji/blob/master/lib/data/shortcuts.js)
- [ ] probably change `:-\` to something else, because of the comment in shortcuts.js … although not sure what this could be
- [ ] we wrap them in some extra ´<span ...>` tags, maybe for padding and font size (?) ... [that's described here](https://github.com/markdown-it/markdown-it-emoji#change-output)
- [ ] testing

**Comment by williamstein** [comment]
- [ ] decide, if we run it for all markdown, or only the ones for chatting (which means to add a boolean parameter)

ALL markdown.  I don't want to have confusion due to inconsistency :-)

- [ ] enable more smilies [upstream shortcut.js file](https://github.com/markdown-it/markdown-it-emoji/blob/master/lib/data/shortcuts.js)

Do that in *another* PR.

- [ ] probably change `:-\` to something else, because of the comment in shortcuts.js … although not sure what this could be

Just remove it.  I don't even know what it is. :-\

- [ ] we wrap them in some extra ´<span ...>` tags, maybe for padding and font size (?) ... [that's described here](https://github.com/markdown-it/markdown-it-emoji#change-output)

Do this in a followup PR.

- [ ] testing

Done by the reviewer.

**Comment by williamstein** [comment]
And another todo for another PR: delete misc.smiley.

**Comment by williamstein** [comment]
Three problems so far in testing:

Doesn't work when preview enabled:
screenshot 2018-08-04 at 8 23 33 am

My fav emoji -- :shrug: is gone:
screenshot 2018-08-04 at 8 22 53 am

Side chat doesn't work yet:
screenshot 2018-08-04 at 8 21 01 am


---

Github solves this problem via unicode and a completions menu... 🤷‍♂️

**Comment by tscholl2** [comment]
I searched for "smiley" in the code, this shows a few other places where the old smiley code is being used:

image

**Comment by williamstein** [comment]
This whole approach to emojis is very bad compared to the solution that Github uses, which is "just make it easy to insert unicode".  That's what we should definitely do... at some point.  It's vastly better, since it requires no markdown extension at all, so it will work with vanilla Jupyter, github, etc.,   Whereas what we are doing here produces docments that only work in cocalc, but won't work when exported to most any other renderer.  The fact that we have so many questions about which emoji's to support, just proves that most markdown renderers will fail on this.  

If we support unicode, you can write emoji's in an .md file when making a blog post (say), and it will work!

So don't put much more effort into this, IMHO, except to fix the bug I reported.

**Comment by williamstein** [comment]
To be clear: I'm fine with this markdown-it approach for now, but we should aim for unicode.

**Comment by williamstein** [comment]
I said:
> This whole approach to emojis is very bad

but @haraldschilly set me straight in video chat.  I'm maybe wrong.

**Pull request closed without merging**
