### PR TITLE
Add missing semicolons (fixes recommendations from LGTM)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
LGTM currently shows more than 400 [alerts for cocalc](https://lgtm.com/projects/g/sagemathinc/cocalc). Some of them are really serious, but require much more work than the trivial changes in the pull request here.

**Comment by haraldschilly** [comment]
well, the last two snippets are in the actual code, but I don't think this is serious. The other changes (assets) are an old talk and well, I wonder why threejs is there. This is probably a directory we should rather get rid of. I have to check …

**Comment by williamstein** [comment]
It seems harmless to merge this.  Add getting rid of the three.js code as a new issue for later?

**Comment by stweil** [comment]
> well, the last two snippets are in the actual code, but I don't think this is serious

None of those missing semicolons is serious. It's more an issue to get uniform code. That's why LGTM classifies it as recommendations.

I think it is good to address recommendations nevertheless, of course without forgetting to address the real errors as well.

**Comment by williamstein** [comment]
> I think it is good to address recommendations nevertheless

It's all merged.

**Comment by williamstein** [comment]
Incidentally, in our own codebase we frequently run prettier with default options, which should always add in semicolons.  Our official style policy for our code is "prettier with the default settings".

**Pull request merged**
