### PR TITLE
Syncdoc history project API export

### PR DESCRIPTION
**Pull request by williamstein**
# Description

# Testing Steps
1.
1.
1.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 093bb5b7912d6e888a84b1f20f2940e238f8f7f6 into 5eeb5243c694840d36c97227b5eb100e8a1fb668 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-635817cc3b9a1f8fdfa90ee7d39e5c19643f9b66)

**new alerts:**

* 1 for Missing rate limiting

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 6b9267729b80f8370667c493b76443167abe6be0 into 5eeb5243c694840d36c97227b5eb100e8a1fb668 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-9516d352b2c7db4a8919fe3ed3aa9ed2fd8924b9)

**new alerts:**

* 1 for Missing rate limiting

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging eb37ec3f50e96d1d95792b9beafa3a6a40582477 into 5eeb5243c694840d36c97227b5eb100e8a1fb668 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-47d343b7b7de0f801fa75d8d9aee245a8d5dd60d)

**new alerts:**

* 1 for Missing rate limiting

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging ca7695bbe622aecef41a31870b762af592d9b7a4 into 5eeb5243c694840d36c97227b5eb100e8a1fb668 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-9fcade802050de6da3deb9a42f7107486279ebe8)

**new alerts:**

* 1 for Missing rate limiting

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by williamstein** [comment]
> 1 for Missing rate limiting

This is now WRONG, and disabling it there didn't work either.

**Pull request merged**
