### PR TITLE
webapp: fix xsl syntax highlighting -- fixes #4613

### LINKED ISSUE #4613: XML highlighting for .xsl files
I do a decent amount of work with XSLT stylesheets, which are XML files usually with the extension `.xsl`. It'd be nice to have XML syntax highlighting for files with that extension. E.g. (from https://en.wikipedia.org/wiki/XSLT )

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:output method="xml" indent="yes"/>

  <xsl:template match="/persons">
    <root>
      <xsl:apply-templates select="person"/>
    </root>
  </xsl:template>

  <xsl:template match="person">
    <name username="{@username}">
      <xsl:value-of select="name" />
    </name>
  </xsl:template>

</xsl:stylesheet>
```

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
see #4613

# Testing Steps
1.
1.
1.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Run eslint on new and edited files
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by williamstein** [comment]
Weird...  I don't understand this fix.  Could you add a comment explaining why the natural solution (that you're deleting) is wrong...?

**Comment by williamstein** [comment]
My guess -there is no codemirror xsl mode.  It simply doesn't exist. Maybe it did at one point and was removed...?

**Comment by haraldschilly** [comment]
maybe, I don't know. it just didn't highlight anything and there is no xsl mode I can find online at the codemirror website.

**Comment by williamstein** [comment]
OK, well this commentary here should be sufficient documentation...

**Pull request merged**
