### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by fchapoton**
mainly imports, all found by lgtm

# Description

# Testing Steps
1.
1.
1.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by haraldschilly** [comment]
This pull request **fixes 8 alerts** when merging 9573bab95c730ecac6bd3d32ea430e6f5ef810e4 into 7cef880c1444b0529b25abee1f0c97e02bc94d5c - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-58a1e3a77e95c9110fcf76613aad135c558bf4ea)

**fixed alerts:**

* 4 for Module is imported more than once
* 2 for Unused local variable
* 1 for Except block handles &#39;BaseException&#39;
* 1 for Suspicious unused loop iteration variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by williamstein** [comment]
@DrXyzzy -- this looks good to me, but could you also look it over and run the test suite; you've been working with this code more than me lately.

**Comment by DrXyzzy** [comment]
@williamstein - yes, starting tests now

**Comment by DrXyzzy** [comment]
Looks good to me.
Also:
baseline pytest of sagews before applying this PR:
```
== 178 passed, 9 skipped in 316.36 seconds ==
```
**and this PR passes all tests as well:**
```
cd ~/cocalc/src
# checkout this pr
cd smc_sagews/smc_sagews/tests
python -m pytest -x
==>
== 178 passed, 9 skipped in 304.31 seconds ==
```

**Pull request merged**
