### PR TITLE
Jupyter explicit kernel

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description
Jupyter notebooks without a kernel or an unknown one are a source of confusion. This patch presents a clear selection dialog with some explanations about what a kernel actually is to the user.

**Reference**: there are two situations the dialog shows up. either user requested, or when opening and the kernel is "bad". here is a side-by-side view of running this in two instances. The dialog only closes  when a kernel is set by itself, when it wasn't opened by the user in the first place.

* [no kernel](https://share.cocalc.com/share/14eed217-2d3c-4975-a381-b69edcb40e0e/scratch/no-kernel.webm?viewer=share)
* [unknown kernel](https://share.cocalc.com/share/14eed217-2d3c-4975-a381-b69edcb40e0e/scratch/unknown-kernel.webm?viewer=share)

# Testing Steps
**important:** switch to experimental image to see the suggestions. 

1. existing notebook with known kernel → this doesn't show up
1. click on kernel info at the top right → kernel "change" dialog shows up
1. open a new ipynb file → dialog asks what to do (slightly different from above)
1. an unknown kernel can be created like that:

```
~$ cat <<EOF > unknown-7.ipynb
{
 "cells": [ ],
 "metadata": {
  "kernelspec": {
   "name": "pythonXY"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
EOF

~$ open unknown-7.ipynb
```

# Relevant Issues
I didn't check

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [x] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [x] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [x] Completely restart Webpack with `./w` in `/src`
- [ ] Screenshots if relevant.

Back end:
- [x] it touches the "project"!

### CODE REVIEW

**Comment by williamstein** [comment]
I tested this (with the experimental image, and after restarting my dev project).  Step 1 of your testing step, namely "existing notebook with known kernel → this doesn't show up" fails in multiple ways.

- Make a new notebook, select kernel, save to disk, duplicate, and open the duplicate.  FAIL -- the select kernel screen shows up anyways.  Saving and mucking around a bit and suddenly it goes away.
- Open an old notebook that I had from 2 months ago. FAIL -- the select kernel screen shows up anyways.
- Click on the bell and click to open a random old notebook from the history in a project that is not running. FAIL seeing this:

image

---

What you're implementing here reminds me of all the *MANY* subtle bugs we had with the default kernel, and kernels changing from what is in the notebook to the default, etc.   They were all very subtle race conditions involving the project and client(s) opening the notebook at the same time, then making decisions.  This kernel selection you're implementing here is like that, but even more difficult... 

For example, what if two people open the same notebook.  If person A selects a kernel, then the "select kernel" screen for person B must properly update.  Your current implementation fails in this case too:

screenshot 2018-11-08 at 4 38 45 pm

I strongly encourage you to spend at least 1-2 more days on this, and either finish it completely so it really works right and is in CoCalc.  Or delete it. One or the other.  Don't let it bitrot!

**Comment by williamstein** [comment]
I also have to wonder -- aren't there a lot of people that only ever use one kernel?   E.g., I imagine basically all sage users only ever use Sage (I'm thinking, e.g., of my phd student Kevin).  With this PR, he'll go from never thinking about kernel selection to having to make a choice and click a button every single time he makes a new notebook.  And he has no possible way out of that added friction -- it would be good to have an account preference to have a default kernel.     (In contrast, Sage worksheets continue to not have extra friction like this.)

**Comment by haraldschilly** [comment]
Hmm, I tested some of what you describe and it worked for me. It's not easy, yes. I'm wondering if what you really mean is a "do not ask again" boolean option. (if it is true && there is a default kernel in the settings → pick it without asking). I'm using that last-kernel setting for the quick selection as the first option, as a  compromise to avoid searching around too much.

I'll look into this, sure.

**Comment by williamstein** [comment]
> Hmm, I tested some of what you describe and it worked for me.

I tested each thing I mentioned multiple times, and usually (maybe always) observed the behavior I described.

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 2e8c299af46cef806dec6b826d128c17cb3b2984 into 5915412db73e9290bb7265a7f018d2586edd7ef8 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-7e39322793a49419673e44981798f3a1a0d27e84)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging a1e19b16e17e6b8c40d60d3ab63a70f7f273648b into 148fc92c78b0009c427b3b9f561e26a255d03d67 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-3823d41533a579f9cb7a4edabcb9cd01f7c01765)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging bd9565a0319120f909a249e7befd96caf53bfe0c into 51303c4997afeaac22d95daa07b3fa9633a6bd61 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-a6cb9abdc94f5c4f1d807b4522718e9f43abe786)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging e8c89882848e8ea198727a6e3d43ff3eb85a041e into dc566c45279267e9584087bb22d8150bcc776c96 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-fa9b5ec403bb9f443939474d6fe01c87c8593af0)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 50699a47e82bf77bdcc504c1ec1e2ed32d691f72 into c38fc660dfacc0bf5c90939782309a0689264c7f - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-b425a3d01ee0af13075efb2fbfa459bcd3fe5aa4)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 9a6dee0cd3f26df72f34bc7dc9b0eb16c8d91f82 into e9c2758edec944ad3fbaf944e6ba6e29486a45c5 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-81e7849337fde3c64cc9b16bcf16212453b171b4)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 2699e6efda28663babc3541f39aaf3f441ad849f into e9c2758edec944ad3fbaf944e6ba6e29486a45c5 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-b8bdf02346b4b95f374ac301fdc6ed3463f1f0db)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 62fc2555b051ae20b1c78c2add76ae62ad242095 into 3f1449742a6ec701bbccf1fe3a933d9816ee28b1 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-f7869b1c133bb53b5fd0eb4c0339875e85536e7b)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging cc06eae60f1c730e4393f97f78b1e06f120cb957 into bffc1c243abb57b142e5158ecb2354ae760b3de7 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-779d1acfc63dde2af9cf47ece6af156394498889)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 11b11eb9da10ed837a8f7be0a4db80d3e167707a into 131b3db410832782829135ceee0c99aec24655af - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-1cec1496745a1381dfec0d9d155ad1bcb01f4d97)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 4efa485d5a7cc1df2cb59b4243332bf0eb18fee0 into afeb31fec8dc61e540258ab65927d5efef16e6c4 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-a54a9f7d730f94d6a4148cd685712976664abfc1)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 9eaa5fb68b6e9f7b78a97d12876249d71e2b39ce into 8ce83a8be8eae352b3be2a8592c9952d5fa7b064 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-9b90b1bafa50ca364a9c717e61efe11e3ca72f16)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging fb6f40436211c3301de54af30beb66b149283f23 into 2493c8b065d5947cfb023b748af5cc14b6857f28 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-f442d6c78a69d9bfb353f17b29ea04617831c81b)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 3 alerts** when merging 950504935a56ea2659dd98a6efaf4cb5d6df790f into 98bd0518464576000dc1ab95ab884718b5e76a2e - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-81e71d40771bda0d824922a3e4bec33533c53cca)

**new alerts:**

* 1 for Comparison between inconvertible types
* 1 for Potentially unsafe external link
* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 5bfcdfd94ee1e7798232bbaec522f1e693dded34 into cf1fd17644fe07181eab6cd43e48aa4a3e646641 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-d11ac9ae129a9c02c8b7b6ea2da410bdc47e69e6)

**new alerts:**

* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 39be01df7ce127b2a4e942b235b479d71164eba5 into d2727595a024629e1638528683922eaa1cebac0d - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-22bdbed3072adf7c584fa4e66cc206482bace25d)

**new alerts:**

* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 3a28c2d633198643989243a344ac17dac4ceb28b into d2727595a024629e1638528683922eaa1cebac0d - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-a596320df4977d108676d5136a16eec65f93d77f)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging f5962024a692b681af1bbe04ad8425c72694a640 into c70b64d58e7483843fb4689ec6f185ee917c0cae - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-a009ab6debd598b123e31b63ef87f1817b026616)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging ca7a21a2e6ea1d502132f8c5785f1df5f0b9eff3 into ddf35db5ce4911d54bc323b7e6d4afee349c6ad3 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-080b2db13ae27c2f2a399138a3ac609aa06147e2)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 642799f939ebe04bf89fb51544241e2e7e75ff94 into ea121b4dbe522026b7b6c54718be19e843b2b6b7 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-caea92da006ee1f256cd6a2f74005b0b8cf5a66a)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 3b0561ad23ea2f985d5a60add3f79ba3a7a198e6 into 3fc14a61f86d1fbec3db036847761a5679f79348 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-f63c62afb3579c582b405e4e5dbf294c1faffae4)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 20b342e6747e617247c6b7d9391d831104025fc0 into 9d3548cf3edd7f10f2168cd8126fd4001e6f4951 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-cf97fc8614350e8a75738718e34f4fcdfd05973e)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging f371e2f9c905365a8af59022fa6fe6b1dcf979cd into c23004ed2489bd2630c37cf0f085d8ed0e089b4b - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-8f38c95b8f3cd10ab67e165ac43d7f6bd6f1bc76)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging beba91e4b760d72615ce991ff8b551683a69bc44 into c23004ed2489bd2630c37cf0f085d8ed0e089b4b - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-a5d562bd284fa0922081218ab918f2b94bd05141)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 2161791ce331b6b81ced39539ae14fc09e2ef470 into 5fbcfd083dead03784886392a9cb0cf0d0d672c0 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-37aa5d17522ef80d31c15e9c5ae7b2319cbbe254)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 41c6e46a8e08aa874ca3c98e8342d10f3e372726 into 0f494c981e1833d78f31de94cbdc0a04d240c799 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-2330c0f0d7833e10c5b45c6debdbda6274d1ec6c)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 95818ab5a49c6b10eb441abf97e88a3a592dde42 into 98b993e4e6a29658a553ff44bb5e61a73a5ce82e - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-9de4f9cb1cb6f905980f48f9c9c08f803c745728)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 44819106cf76f359b6571d3fbc1de3cf4af669fe into f5827a72ca995f7d7a48d857f03965af237ef67e - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-6ff307f0c64a9d50b5a74e59ec2a2f8a114f436a)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 38bf54630bcfb5c1ad0058cabf06322271a91d72 into f5827a72ca995f7d7a48d857f03965af237ef67e - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-767de5eb7138df4aba3424e06ecc4e10e22fc6da)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 8b9e86f37a95d2afdd4c5ef2a36cb057bb951884 into 9307736278e40f3ffd80b55ee3dfd1e650258e5b - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-228f498c3162da518b454e39af2fedfe9da81432)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 984dd845526989b5b19dc927739aa10345954ba5 into 91d2639918a99d839b74ebcfff9f0ac5a1ea8c03 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-8c2ce4c4aad1e75faef43353c8382ed7e85fc940)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 303d3d894394f1b9cfed98c271c3e6bbfd605c98 into b0df27e99b5081b270a4c40aafbcb775d3ee0f5b - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-1d4bf4c8cebfb802034a8eb393dc2450516d9b8e)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging f6d5202753edc0718f5ec1e51fb978636205e752 into d412a05c9453cd5c3271b4a518deb1da7510d84f - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-1c3c38dc728bb0d88b397a93a9bf9694196cd137)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging f72380d4ec9f19ff73f0cccbe4777d980b5d4b10 into 1a1f0261629ac02c84af36cee1d99e13a8f0d0a8 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-f2c3695a98eec953ecafe3bb0735601fe93d6c0f)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 906749d9894bf1248695be05e648b5f6dda905bb into 9a78ddcf7bababc3abefe72825cb59601f5bb5d6 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-354c25ef7eaae222aebfa9f9dc33cab202c97026)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 2 alerts** when merging 6d5823f5a957f30e4c84877ca3f691309577b8ad into 0a3e65531257d06360217fa4df1c78fd83cbf543 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-87385649920fa811568664b4f2ef6e6a593cdedb)

**new alerts:**

* 1 for Assignment to constant
* 1 for Comparison between inconvertible types

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by williamstein** [comment]
I didn't realize this is needs review.  I'm refactoring a lot of relevant code which will directly conflict with this.   Ugh.

**Comment by williamstein** [comment]
Merged.  This is really good.  Any bitrot/merge conflicts are on me now.

**Pull request merged**
