### PR TITLE
next/config: fixing style, adding email verification, ...

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

- next/config: name, etc.
- next/config: account
- I saw email verification is still missing, and I added it. screenshot from  config/account/email:
     Screenshot from 2023-01-25 15-47-12
-  This depends on the hub, so, I added this as a reference. I believe that's against the overall plan, but well, there are already warnings about circular dependencies, and this only adds a bit more of these. In any case, this works.
- While implementing the above, I struggled with some postgres typing. Being more specific with some types opened up a can of worms. e.g. now it is possible to specify the expected type of a query/async_query. So, many additional touches to files, but none of them should have any impact (famous last words :shrug:)

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by williamstein** [comment]
> I believe that's against the overall plan, but well, there are already warnings about circular dependencies, and this only adds a bit more of these. In any case, this works.

Those warnings are from pnpm, since in some cases pnpm install with workspaces can't handle circular deps.  They don't seem to be a problem for us, due to the explicit rules I put in workspaces.py.   

Regarding the actual Javascript/Typescript dependencies, since we're mostly using import now (instead of require), circular dependencies aren't a problem.

That said, I often view circular dependencies as a good opportunity to refactor.  In particular, this code for email verification should maybe be moved to packages/server, and then hub and next both use that.

**Comment by williamstein** [comment]
> This depends on the hub.

I now see looking at your code that you made @cocalc/server depend on @cocalc/hub by adding this line:

```ts
import { verify_email_send_token } from "@cocalc/hub/auth";
```

I don't like this at all.  This breaks building our kucalc manage-* image, since the Dockerfile to do that contains:

```sh
RUN cd /home/manage/cocalc/src && \
  export PACKAGES="util,database,backend,server" && \
  ./workspaces.py install --packages=$PACKAGES && \
  ./workspaces.py build --packages=$PACKAGES
```

Notice that we'll have to add more packages to the above, and that'll significantly increase build time and size.

I realize it's a lot of work to refactor the code to move `verify_email_send_token` to @cocalc/server, where it belongs.

I guess we can temporarily just make building manage-* worse...

Any thoughts?

**Comment by williamstein** [comment]
I think i'll merge this and if the dep on hub causes too much trouble, then I'll just comment that part of the PR out and we can fix it later.

**Comment by haraldschilly** [comment]
I full agree, this is not ideal and should be refactored. It's not that easy, because that  code I saw depends on a coffee file, and who knows what else. My more general direction is to redo the entire "emailing" aspect in a "server" subdirectory, remove any dependency on external templates – and instead use something to handle email templates by the application itself and hence make them configurable for 3rd parties.

**Pull request merged**
