### PR TITLE
adding custom global type defs for cocalc

### PR DESCRIPTION
**Pull request by haraldschilly**
quick attempt to add declarations for `$`, `window` and so on.

ideas from here: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

interestingly, this doesn't work for `window.app_base_url` in `jupyter/server-urls.ts`. So, despite that I can start the hub in my dev project, maybe all this isn't working at all.

### CODE REVIEW

**Comment by williamstein** [comment]
This completely breaks starting projects:
```
~/projects/7424391a-0a88-4a6e-a486-2d9e90a17281$ more .smc/local_hub/local_hub.log
2018-08-16T18:58:20.632Z - debug: jupyter BlobStore: constructor
2018-08-16T18:58:20.638Z - debug: jupyter BlobStore: /home/user/projects/7424391a-0a88-4a6e-a486-2d9e90a17281/.jupyter-blobs-v0.db opened fine
TSError: ⨯ Unable to compile TypeScript
home/user/cocalc/src/smc-webapp/jupyter/actions.ts (210,15): Cannot find name 'window'. (2304)
home/user/cocalc/src/smc-webapp/jupyter/actions.ts (210,41): Cannot find name 'window'. (2304)
home/user/cocalc/src/smc-webapp/jupyter/actions.ts (211,12): Cannot find name 'window'. (2304)
home/user/cocalc/src/smc-webapp/jupyter/actions.ts (1808,16): Cannot find name 'localStorage'. (2304)
home/user/cocalc/src/smc-webapp/jupyter/actions.ts (1808,48): Cannot find name 'localStorage'. (2304)
home/user/cocalc/src/smc-webapp/jupyter/actions.ts (1809,21): Cannot find name 'localStorage'. (2304)
home/user/cocalc/src/smc-webapp/jupyter/actions.ts (1820,15): Cannot find name 'localStorage'. (2304)
home/user/cocalc/src/smc-webapp/jupyter/actions.ts (2229,7): Cannot find name 'window'. (2304)
    at getOutput (/home/user/cocalc/src/smc-project/node_modules/ts-node/dist/index.js:241:23)
    at Object.compile (/home/user/cocalc/src/smc-project/node_modules/ts-node/dist/index.js:366:18)
    at Module.m._compile (/home/user/cocalc/src/smc-project/node_modules/ts-node/dist/index.js:292:49)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/user/cocalc/src/smc-project/node_modules/ts-node/dist/index.js:294:16)
    at Module.load (/home/user/cocalc/src/smc-project/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/cocalc/src/smc-webapp
```

Let me know when you've fixed that and tested everything thoroughly.

ALSO, is there any way to not change jupyter/actions.ts, since your changes there massively conflict with my wsproj branch.

**Comment by haraldschilly** [comment]
ok, just 3 lines in actions.ts, and I cleaned up all the mess that was going on. with that here, I am able to eval a couple of cells in a cc-in-cc project (after restarting everything at least once). but I'm not sure what a proper procedure would be, and the internet wasn't as helpful with that as I wished.

**Comment by williamstein** [comment]
@haraldschilly  can you confirm that you fully tested building and running this on k2? Then I'm happy to merge...   Just set COCALC_BRANCH env var, then build manage, hub, project, and static.... and update the project image tag.

**Comment by haraldschilly** [comment]
No, I haven't tested this, and I don't know if what I did is even ok to do. The documentation is not clear to me, and what I tried first with setting the type roots in the tsconfig file didn't work. This here might have the touch of being a quick fix.

**Comment by haraldschilly** [comment]
ok, k2 is open for testing. I hope setting the env var did work everywhere as expected. A good indicator is that e.g in a project `/cocalc/src/smc-project/globals.d.ts` exists.

**Pull request merged**
