### PR TITLE
Remove smc-react.coffee and Type Project_store

### PR DESCRIPTION
**Pull request by johnjeng**
Finally seems to run correctly. Code needs some cleaning up still.

@DrXyzzy could you help test this?

# Known Issues
- [x] Creating files from the `+ New` Page doesn't work
- [x] Creating files from project listings doesn't work
- [x] Project Actions is just totally broken. Okay

### CODE REVIEW

**Comment by DrXyzzy** [comment]
@j3, "test everything" is a lot. :-) What things do you think most need testing? I'll log the results as I go along.

**Comment by johnjeng** [comment]
@DrXyzzy Right. Haha. Specifically I had in mind Sagews and Jupyter stuff.

**Comment by johnjeng** [comment]
@DrXyzzy Hold off on testing. Lots of stuff broken.

**Comment by williamstein** [comment]
>  I'll log the results as I go along.

Maybe some of what you end up doing can later be automated with mocha...

**Comment by johnjeng** [comment]
@DrXyzzy This is ready to undergo some testing.

**Comment by DrXyzzy** [comment]
@johnjeng, are the 3 "known issues" at the top of this PR supposed to be fixed now? They were not when I checked a few hours ago, before the last few commits. For example, when I checked out the branch for this PR and built cc-in-cc, I could not create files from (+) New or Files tab.

**Comment by johnjeng** [comment]
@DrXyzzy They should be fixed. Though if it returns with an error that isn't `failed` then that's not an issue I'm aware of.

**Pull request merged**
