### PR TITLE
frontend/course: inherit environment variables

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

ref: #5357

blocked: backend must be deployed first → ok, all done
- [x] kucalc 
- [x] cocalc-cloud

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by williamstein** [comment]
This fixes https://github.com/sagemathinc/cocalc/issues/5357

**Comment by vdtoorn** [comment]
Question: I see the code, but I can't see the option in the course configuration, am I missing something?

**Comment by vdtoorn** [comment]
OK, then I must be on a wrong "tier", I'm using the dockerized version and it's not there. Sorry for that!

**Comment by haraldschilly** [comment]
> OK, then I must be on a wrong "tier", I'm using the dockerized version and it's not there. Sorry for that!

Yes, I see, a few functionalities, in particular any more advanced functionality that deals with running projects (container quotas, env variables, timeout management, ...) is only available on cocalc.com and the kubernetes based on-prem version. I've created a ticket about this, mainly to record this as a missing detail: https://github.com/sagemathinc/cocalc/issues/5797

**Pull request merged**
