### PR TITLE
db/backend: respect SMC_DB env var in Client and Pool via "data" object

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

what's left is to test this

ok, and I am still confused with those versions. hub's reference to the database package is still the old one. how do I update those versions? does this only work after this PR is merged, because it depends on what's published at npm?

## [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Testing instructions are provided, if not obvious
- [ ] Release instructions are provided, if not obvious

### CODE REVIEW

**Comment by haraldschilly** [comment]
well, I don't know really what the next steps are. I published backend and database with the tag `pr5560`. then updated them for the hub via `npm i --save @cocalc/database@1.0.0` and `npm i --save @cocalc/backend@2.0.0`. … which ends up as this in the packages file:

```
"@cocalc/backend": "file:../backend",
"@cocalc/database": "file:../database",
```

so, I'll edit the file manually and see what's happening. feels wrong.

**Comment by haraldschilly** [comment]
Something is wrong with this PR. I first updated backend and database, published to npm with the `pr5560` tag. Then I updated hub's package.json with the newer version numbers. My motivation is to get the newer code when I install the hub as part of the docker install, i.e. npm install with that tag. Upon launching the server, before code gets even executed, this happens:

```
Error: A metric with the name cocalc_database_query_queue_executed_total has already been registered.
    at Registry.registerMetric (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/registry.js:80:10)
    at new Metric (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/metric.js:48:13)
    at new Counter (/cocalc/lib/node_modules/@cocalc/hub/node_modules/prom-client/lib/counter.js:12:1)
    at Object.newCounter (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/database/metrics.ts:13:10)
    at Object.<anonymous> (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/database/dist/postgres-user-query-queue.js:49:30)
    at Object.<anonymous> (/cocalc/lib/node_modules/@cocalc/hub/node_modules/@cocalc/database/dist/postgres-user-query-queue.js:263:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

**Comment by haraldschilly** [comment]
I give up. I removed my changes to the package files, here is just the code. The final nail in the coffin was: `packages/hub/package-lock.json is HUGE! Refusing to do anything further.`

**Comment by williamstein** [comment]
Can you make a version of this branch that has just the commit with your changes.  I'm not merging another bunch of 50MB+ package-lock files into our repo history.  This happened once when I missed it (for a week or two) and wastes a lot of space forever, and also makes git checkout longer.

**Comment by haraldschilly** [comment]
→ https://github.com/sagemathinc/cocalc/pull/5562

**Pull request closed without merging**
