### PR TITLE
Open cocalc

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

# Testing Steps
1.
1.
1.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging ad5ff5ab0764ccc151a3bcac7f2351ef406b1183 into e43d2f9667d6df4be9b22b7c66eb55fec123f0b6 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-50c2ccfafba68b0947770b3d5dc425a28264322a)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging e84ec2267000211291069591eea03f70a3ce994d into e43d2f9667d6df4be9b22b7c66eb55fec123f0b6 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-01f4528f9a703824e543df93d968dc2f423595f6)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 6c3e28758f40c1ad8eb6674173f63f2f1d1596f1 into e43d2f9667d6df4be9b22b7c66eb55fec123f0b6 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-dccaffe8c756e2244882cbe0bb3a8dccc5c877eb)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 84a4000079de8bc08262f1e3b7b197474151d6e3 into d2727595a024629e1638528683922eaa1cebac0d - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-2b21ee487f65b865ce03f26029bab70b09f888f2)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 0f0ea76f46c57b12db35ed843b7f73ccde511e6f into d2727595a024629e1638528683922eaa1cebac0d - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-db1e05857a0a999dad2828d8e0ba1c4f0d676ceb)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 67265258ec15c14a9ad1ba6360b11e7c21692ccb into 78c0d41311fae8288c2632772c2421e1513f9e64 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-2eb08113315802d92e74f14afe9c965a762c32c2)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 9b742535c9289a79cfc376f49b7f47b8456ab117 into c70b64d58e7483843fb4689ec6f185ee917c0cae - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-b80c6f8fdf8d0ed13d2495f55cf4d8a29030781d)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging ef6b7e4a38c10e4dd4125b9f7b7e2e38f8980ee8 into ddf35db5ce4911d54bc323b7e6d4afee349c6ad3 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-fad57b777b7fcb97a4b2535c38025b67054b0eac)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging 61b85155b8c0ed2942e78a38fe3cfc56c617e12b into 0f494c981e1833d78f31de94cbdc0a04d240c799 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-4dfb35097e3f4cd23fec4304aef04fab290e1cb2)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by williamstein** [comment]
1. @haraldschilly  -- What precisely is left to do on this?   When will it be done?

Skimming through the code, I'm mostly annoyed to see a lot of new coffeescript and pug templates... but I guess (?) that's mostly refactoring of existing code, or trying to minimize changes.

2. @haraldschilly  -- What exactly is being changed?

**Comment by haraldschilly** [comment]
This pull request **fixes 5 alerts** when merging 15bb7b71a678760e13afb307d73e42a4eedf8c51 into 7bb5050da3965da048de682f2461add67ef52ea5 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-8c86968a9f56d168c622c2c9966dc9765936fa32)

**fixed alerts:**

* 2 for Module imports itself
* 1 for &#39;import \*&#39; may pollute namespace
* 1 for Inconsistent equality and hashing
* 1 for Result of integer division may be truncated

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by haraldschilly** [comment]
This pull request **fixes 5 alerts** when merging 2227cb5142663b20b80f876d4773e0377ba3b949 into 02bfc1e7041ca2d9f19950c10ad37a6d3003b1f5 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-03355fb572e0a26b8113d279680feb3b2181056e)

**fixed alerts:**

* 2 for Module imports itself
* 1 for &#39;import \*&#39; may pollute namespace
* 1 for Inconsistent equality and hashing
* 1 for Result of integer division may be truncated

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request closed without merging**
