### PR TITLE
Docker image: Install Julia 0.6 and the IJulia kernel

### PR DESCRIPTION
**Pull request by tornaria**
NOTE: this is intended to be a single commit on top of PR #2294, but I don't know how to make dependent pull requests.

The relevant commit is b037aa2, which in two steps:
 * installs Julia 0.6 from the official binary
 * installs IJulia kernel using julia package management

It may be desirable to preinstall other julia packages, that should be very easy copying what I did to install IJulia, something like:
```
# Install julia packages
RUN echo '\
ENV["JULIA_PKGDIR"] = "/opt/julia-903644385b/share/julia/site"; \
Pkg.init(); \
Pkg.add("package1"); \
Pkg.add("package2"); \
... 
Pkg.add("packageN");' | julia
```

### CODE REVIEW

**Comment by williamstein** [comment]
We are focused on a major new backend release right now, and aren't doing much else until that is done.

**Comment by haraldschilly** [comment]
I'm wondering if we should promote this docker dev subdirectory to its own github repo, e.g. `cocalc-docker`.

**Comment by williamstein** [comment]
Yes, that's a good idea -- there's very little coupling between it and cocalc itself.

**Comment by tornaria** [comment]
https://github.com/tornaria/cocalc-docker

**Comment by tornaria** [comment]
I created the above repo doing:
```
git filter-branch --prune-empty --subdirectory-filter src/dev/docker/ master
```
so it preserves the history of the subdirectory.

**Comment by haraldschilly** [comment]
yes, looks good, but can we transfer your repository to us here? for that, you have to transfer ownership (in the settings) to me `haraldschilly` and then I transfer it here. The issue you created will move along the way.

**Comment by williamstein** [comment]
We should close the two PR's here, and you should make them to the new repo, when it is setup.

**Comment by williamstein** [comment]
And I like everything you did in this PR...

**Comment by tornaria** [comment]
I've just transfered my new repo 'cocalc-docker' to haraldschilly, you can pick up from there.

Note that in that repo I made 3 PR of which I merged two into a branch "devel", but the branch "master" is pristine as it was produced by the filter-branch command.

The remaining PR is about having letsencrypt integration, it's working for me and I think it should work fine in general, but I haven't done extensive testing.

Let me know if you have any problem with the transfer (and if you prefer to rerun the above "filter-branch" command, that's fine with me, the way it works it will result in the exact same commits so the repos will be compatible, in that case I will redo all my PR in your repo).

**Comment by tornaria** [comment]
Closed because of https://github.com/tornaria/cocalc-docker/pull/2

**Pull request closed without merging**
