### PR TITLE
Add new location to see your mentions

### PR DESCRIPTION
**Pull request by johnjeng**
# Description
Currently:
Screen Shot 2019-04-18 at 6 54 26 PM

UI for no mentions:
Screen Shot 2019-04-18 at 6 55 04 PM

# Testing Steps
Do this with 2 accounts open. One will be the mentioner and the other the mentioned.
The mentioned person should have the notifications page open.

1. Mention with
    1. a very long comment and short comment
    1. the mention is at the beginning, middle, or end.
1. Change the mentioner's name
1. Change the project title
1. Mention them in another project. The mention should appear at the top of the list.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] No debugging console.log messages.
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by haraldschilly** [comment]
This pull request **introduces 1 alert** when merging b270a09ca9d61dc5daad044a7050f19d3976ffbe into 4162ae3c56d6cb2fa67e85f413fb131892104ea7 - [view on LGTM.com](https://lgtm.com/projects/g/sagemathinc/cocalc/rev/pr-c9b39e2e26620ccc8d00d39887e14b5dbfbf33d5)

**new alerts:**

* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by DrXyzzy** [comment]
I found the following so far while testing in cc-in-cc instance provided by @johnjeng:

- Create a new account. Then click on the notification bell before creating any projects. You get a blank browser window. Refresh gets rid of the blank window.

- In a project, create a file, then open it by clicking on it from Files. You & collaborators on the project will get a notification, but there's nothing after "edited by":

edited-by

I'll keep testing.

**Comment by DrXyzzy** [comment]
3. Collaborator A in some project just opens `foo3.tex`, does not edit anything. Collaborator B on the same project gets this notification about `.foo3.tex.syncdb` being edited.

Screen Shot 2019-04-22 at 3 44 39 PM

**Comment by williamstein** [comment]
The first crash @DrXyzzy pointed out is a blocker for this, so I'm not merging it today (and it is definitely introduced by this PR):

image

**Comment by williamstein** [comment]
(and nice job @DrXyzzy finding that!)

**Pull request merged**
