### PR TITLE
phase 2: removing landing pages

### PR DESCRIPTION
**Pull request by haraldschilly**
# Description

included in this package
* removes most of our landing pages, they're in the hub-landing plugin now
* adds a bit more customization
* replaces the index page with a shorter page, which is a lot more customizable
* enhances the signin-landing page (logo, banner, etc.)
* tweaks to the about page (logo, banner, name, support contact, etc.)
* footer
* there are also changes to the initial loading banner. i.e. it's as usual if there is nothing configured. otherwise, it spells out the site name, support email address, and of course, the images

more general
* what's interesting: I see new typescript warnings. not sure why they pop up. I'll fix them as well.
* once this is merged, hub-landing requires a small patch as well

## rollout
1. hub first
2. then static

# Testing Steps
* **in any case, testing this requires to check this thoroughly in "test". I've not done that yet.**
* opening all application pages
* sign in works, including password reset
* index page, also to check that elements like the terms of service link only show up, if there is a ToS url set
* relevant for cocalc.com: removing all site settings except details like help email and the terms of service information string, should not change anything (loading banner, about, signin landing page...)

# Screenshots

index page

screenshot-cocalc com-2020 03 23-14_47_32

about page

Screenshot from 2020-03-23 14-50-02

loading banner

Screenshot from 2020-03-23 14-51-15

Screenshot from 2020-03-23 14-52-12

landing page (pale blue background is necessary to avoid having to define 4 images, instead of 2)

Screenshot from 2020-03-23 14-53-18

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Run eslint on new and edited files
- [ ] All new code is actually used.
- [ ] Non-obvious code has some sort of comments.

Front end:
- [ ] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [ ] Completely restart Webpack with `./w` in `/src`
- [ ] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

**Comment by williamstein** [comment]
> in any case, testing this requires to check this thoroughly in "test". I've not done that yet.

Can you do that, then tell me that it worked perfectly (or not)?  Then i'll double check things myself and merge.

**Comment by haraldschilly** [comment]
I tested this in "test". Had to tweak the static service a little bit and it's imho ready to be merged.

**Comment by haraldschilly** [comment]
hmm, I take that back, the favicon is off. I'll have to check this…

**Comment by williamstein** [comment]
@haraldschilly -- I looked over the code and tested it a little (on test.cocalc.com), and it looks like a massive improvement to me.  Can YOU please go ahead and merge it into master and release it in production?

**Pull request merged**
